service:
  name: blueprint
  domain: core

  logging:
    level: debug

  network:
    bind_port: 2221

badger:
  path: tmp/

raft:
  node-id: node_1
  address: localhost
  port: 1111
  bootstrap: true
