// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/crud/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_CREATE      Operation = 1
	Operation_OPERATION_UPDATE      Operation = 2
	Operation_OPERATION_DELETE      Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_CREATE",
		2: "OPERATION_UPDATE",
		3: "OPERATION_DELETE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_CREATE":      1,
		"OPERATION_UPDATE":      2,
		"OPERATION_DELETE":      3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_crud_v1_events_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_examples_crud_v1_events_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_examples_crud_v1_events_proto_rawDescGZIP(), []int{0}
}

type DatabaseModelSaved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Operation     Operation              `protobuf:"varint,3,opt,name=operation,proto3,enum=examples.crud.v1.Operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseModelSaved) Reset() {
	*x = DatabaseModelSaved{}
	mi := &file_examples_crud_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseModelSaved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseModelSaved) ProtoMessage() {}

func (x *DatabaseModelSaved) ProtoReflect() protoreflect.Message {
	mi := &file_examples_crud_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseModelSaved.ProtoReflect.Descriptor instead.
func (*DatabaseModelSaved) Descriptor() ([]byte, []int) {
	return file_examples_crud_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseModelSaved) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *DatabaseModelSaved) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *DatabaseModelSaved) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

var File_examples_crud_v1_events_proto protoreflect.FileDescriptor

const file_examples_crud_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1dexamples/crud/v1/events.proto\x12\x10examples.crud.v1\"\x89\x01\n" +
	"\x12DatabaseModelSaved\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x129\n" +
	"\toperation\x18\x03 \x01(\x0e2\x1b.examples.crud.v1.OperationR\toperation*h\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_CREATE\x10\x01\x12\x14\n" +
	"\x10OPERATION_UPDATE\x10\x02\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x03B4Z2github.com/steady-bytes/draft/api/examples/crud/v1b\x06proto3"

var (
	file_examples_crud_v1_events_proto_rawDescOnce sync.Once
	file_examples_crud_v1_events_proto_rawDescData []byte
)

func file_examples_crud_v1_events_proto_rawDescGZIP() []byte {
	file_examples_crud_v1_events_proto_rawDescOnce.Do(func() {
		file_examples_crud_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_crud_v1_events_proto_rawDesc), len(file_examples_crud_v1_events_proto_rawDesc)))
	})
	return file_examples_crud_v1_events_proto_rawDescData
}

var file_examples_crud_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_crud_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_crud_v1_events_proto_goTypes = []any{
	(Operation)(0),             // 0: examples.crud.v1.Operation
	(*DatabaseModelSaved)(nil), // 1: examples.crud.v1.DatabaseModelSaved
}
var file_examples_crud_v1_events_proto_depIdxs = []int32{
	0, // 0: examples.crud.v1.DatabaseModelSaved.operation:type_name -> examples.crud.v1.Operation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_crud_v1_events_proto_init() }
func file_examples_crud_v1_events_proto_init() {
	if File_examples_crud_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_crud_v1_events_proto_rawDesc), len(file_examples_crud_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_crud_v1_events_proto_goTypes,
		DependencyIndexes: file_examples_crud_v1_events_proto_depIdxs,
		EnumInfos:         file_examples_crud_v1_events_proto_enumTypes,
		MessageInfos:      file_examples_crud_v1_events_proto_msgTypes,
	}.Build()
	File_examples_crud_v1_events_proto = out.File
	file_examples_crud_v1_events_proto_goTypes = nil
	file_examples_crud_v1_events_proto_depIdxs = nil
}
