// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: core/message_broker/actors/v1/consumer.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConsumeRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConsumeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConsumeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConsumeRequestMultiError,
// or nil if none found.
func (m *ConsumeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConsumeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConsumeRequestValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConsumeRequestValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConsumeRequestValidationError{
				field:  "Message",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Count != nil {

		if all {
			switch v := interface{}(m.GetCount()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConsumeRequestValidationError{
						field:  "Count",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConsumeRequestValidationError{
						field:  "Count",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCount()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConsumeRequestValidationError{
					field:  "Count",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ConsumeRequestMultiError(errors)
	}

	return nil
}

// ConsumeRequestMultiError is an error wrapping multiple validation errors
// returned by ConsumeRequest.ValidateAll() if the designated constraints
// aren't met.
type ConsumeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConsumeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConsumeRequestMultiError) AllErrors() []error { return m }

// ConsumeRequestValidationError is the validation error returned by
// ConsumeRequest.Validate if the designated constraints aren't met.
type ConsumeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConsumeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConsumeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConsumeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConsumeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConsumeRequestValidationError) ErrorName() string { return "ConsumeRequestValidationError" }

// Error satisfies the builtin error interface
func (e ConsumeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConsumeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConsumeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConsumeRequestValidationError{}

// Validate checks the field values on ConsumeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConsumeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConsumeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConsumeResponseMultiError, or nil if none found.
func (m *ConsumeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ConsumeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConsumeResponseValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConsumeResponseValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConsumeResponseValidationError{
				field:  "Message",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ConsumeResponseMultiError(errors)
	}

	return nil
}

// ConsumeResponseMultiError is an error wrapping multiple validation errors
// returned by ConsumeResponse.ValidateAll() if the designated constraints
// aren't met.
type ConsumeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConsumeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConsumeResponseMultiError) AllErrors() []error { return m }

// ConsumeResponseValidationError is the validation error returned by
// ConsumeResponse.Validate if the designated constraints aren't met.
type ConsumeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConsumeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConsumeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConsumeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConsumeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConsumeResponseValidationError) ErrorName() string { return "ConsumeResponseValidationError" }

// Error satisfies the builtin error interface
func (e ConsumeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConsumeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConsumeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConsumeResponseValidationError{}
