// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file core/message_broker/actors/v1/consumer.proto (package core.message_broker.actors.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ConsumeRequest, ConsumeResponse } from "./consumer_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The `Consumer` registers the messages that it cares about with `INSERT_PRODUCT_NAME`.
 *
 * @generated from service core.message_broker.actors.v1.Consumer
 */
export const Consumer = {
  typeName: "core.message_broker.actors.v1.Consumer",
  methods: {
    /**
     * @generated from rpc core.message_broker.actors.v1.Consumer.Consume
     */
    consume: {
      name: "Consume",
      I: ConsumeRequest,
      O: ConsumeResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

