// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/message_broker/actors/v1/metrics.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopicSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	WindowSeconds int32                  `protobuf:"varint,2,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicSeriesRequest) Reset() {
	*x = GetTopicSeriesRequest{}
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicSeriesRequest) ProtoMessage() {}

func (x *GetTopicSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetTopicSeriesRequest) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopicSeriesRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GetTopicSeriesRequest) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

type SeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesPoint) Reset() {
	*x = SeriesPoint{}
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesPoint) ProtoMessage() {}

func (x *SeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesPoint.ProtoReflect.Descriptor instead.
func (*SeriesPoint) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *SeriesPoint) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *SeriesPoint) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTopicSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*SeriesPoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	BucketSecs    int32                  `protobuf:"varint,2,opt,name=bucket_secs,json=bucketSecs,proto3" json:"bucket_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicSeriesResponse) Reset() {
	*x = GetTopicSeriesResponse{}
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicSeriesResponse) ProtoMessage() {}

func (x *GetTopicSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetTopicSeriesResponse) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopicSeriesResponse) GetPoints() []*SeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *GetTopicSeriesResponse) GetBucketSecs() int32 {
	if x != nil {
		return x.BucketSecs
	}
	return 0
}

type GetMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// window_seconds is the lookback window for all metrics. 0 defaults to 300 (5 min).
	WindowSeconds int32 `protobuf:"varint,1,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricsRequest) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

// EdgeVolume reports the event count for one (source, event_type) pair.
type EdgeVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeVolume) Reset() {
	*x = EdgeVolume{}
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeVolume) ProtoMessage() {}

func (x *EdgeVolume) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeVolume.ProtoReflect.Descriptor instead.
func (*EdgeVolume) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *EdgeVolume) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EdgeVolume) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EdgeVolume) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetMetricsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EdgeVolumes         []*EdgeVolume          `protobuf:"bytes,1,rep,name=edge_volumes,json=edgeVolumes,proto3" json:"edge_volumes,omitempty"`
	MedianLatencyMs     float64                `protobuf:"fixed64,2,opt,name=median_latency_ms,json=medianLatencyMs,proto3" json:"median_latency_ms,omitempty"`
	P95LatencyMs        float64                `protobuf:"fixed64,3,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	TotalMessagesPerMin uint32                 `protobuf:"varint,4,opt,name=total_messages_per_min,json=totalMessagesPerMin,proto3" json:"total_messages_per_min,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetricsResponse) GetEdgeVolumes() []*EdgeVolume {
	if x != nil {
		return x.EdgeVolumes
	}
	return nil
}

func (x *GetMetricsResponse) GetMedianLatencyMs() float64 {
	if x != nil {
		return x.MedianLatencyMs
	}
	return 0
}

func (x *GetMetricsResponse) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalMessagesPerMin() uint32 {
	if x != nil {
		return x.TotalMessagesPerMin
	}
	return 0
}

var File_core_message_broker_actors_v1_metrics_proto protoreflect.FileDescriptor

const file_core_message_broker_actors_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"+core/message_broker/actors/v1/metrics.proto\x12\x1dcore.message_broker.actors.v1\"]\n" +
	"\x15GetTopicSeriesRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12%\n" +
	"\x0ewindow_seconds\x18\x02 \x01(\x05R\rwindowSeconds\"F\n" +
	"\vSeriesPoint\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"}\n" +
	"\x16GetTopicSeriesResponse\x12B\n" +
	"\x06points\x18\x01 \x03(\v2*.core.message_broker.actors.v1.SeriesPointR\x06points\x12\x1f\n" +
	"\vbucket_secs\x18\x02 \x01(\x05R\n" +
	"bucketSecs\":\n" +
	"\x11GetMetricsRequest\x12%\n" +
	"\x0ewindow_seconds\x18\x01 \x01(\x05R\rwindowSeconds\"Y\n" +
	"\n" +
	"EdgeVolume\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"\xe9\x01\n" +
	"\x12GetMetricsResponse\x12L\n" +
	"\fedge_volumes\x18\x01 \x03(\v2).core.message_broker.actors.v1.EdgeVolumeR\vedgeVolumes\x12*\n" +
	"\x11median_latency_ms\x18\x02 \x01(\x01R\x0fmedianLatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x03 \x01(\x01R\fp95LatencyMs\x123\n" +
	"\x16total_messages_per_min\x18\x04 \x01(\rR\x13totalMessagesPerMin2\xff\x01\n" +
	"\aMetrics\x12s\n" +
	"\n" +
	"GetMetrics\x120.core.message_broker.actors.v1.GetMetricsRequest\x1a1.core.message_broker.actors.v1.GetMetricsResponse\"\x00\x12\x7f\n" +
	"\x0eGetTopicSeries\x124.core.message_broker.actors.v1.GetTopicSeriesRequest\x1a5.core.message_broker.actors.v1.GetTopicSeriesResponse\"\x00BAZ?github.com/steady-bytes/draft/api/core/message_broker/actors/v1b\x06proto3"

var (
	file_core_message_broker_actors_v1_metrics_proto_rawDescOnce sync.Once
	file_core_message_broker_actors_v1_metrics_proto_rawDescData []byte
)

func file_core_message_broker_actors_v1_metrics_proto_rawDescGZIP() []byte {
	file_core_message_broker_actors_v1_metrics_proto_rawDescOnce.Do(func() {
		file_core_message_broker_actors_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_message_broker_actors_v1_metrics_proto_rawDesc), len(file_core_message_broker_actors_v1_metrics_proto_rawDesc)))
	})
	return file_core_message_broker_actors_v1_metrics_proto_rawDescData
}

var file_core_message_broker_actors_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_message_broker_actors_v1_metrics_proto_goTypes = []any{
	(*GetTopicSeriesRequest)(nil),  // 0: core.message_broker.actors.v1.GetTopicSeriesRequest
	(*SeriesPoint)(nil),            // 1: core.message_broker.actors.v1.SeriesPoint
	(*GetTopicSeriesResponse)(nil), // 2: core.message_broker.actors.v1.GetTopicSeriesResponse
	(*GetMetricsRequest)(nil),      // 3: core.message_broker.actors.v1.GetMetricsRequest
	(*EdgeVolume)(nil),             // 4: core.message_broker.actors.v1.EdgeVolume
	(*GetMetricsResponse)(nil),     // 5: core.message_broker.actors.v1.GetMetricsResponse
}
var file_core_message_broker_actors_v1_metrics_proto_depIdxs = []int32{
	1, // 0: core.message_broker.actors.v1.GetTopicSeriesResponse.points:type_name -> core.message_broker.actors.v1.SeriesPoint
	4, // 1: core.message_broker.actors.v1.GetMetricsResponse.edge_volumes:type_name -> core.message_broker.actors.v1.EdgeVolume
	3, // 2: core.message_broker.actors.v1.Metrics.GetMetrics:input_type -> core.message_broker.actors.v1.GetMetricsRequest
	0, // 3: core.message_broker.actors.v1.Metrics.GetTopicSeries:input_type -> core.message_broker.actors.v1.GetTopicSeriesRequest
	5, // 4: core.message_broker.actors.v1.Metrics.GetMetrics:output_type -> core.message_broker.actors.v1.GetMetricsResponse
	2, // 5: core.message_broker.actors.v1.Metrics.GetTopicSeries:output_type -> core.message_broker.actors.v1.GetTopicSeriesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_message_broker_actors_v1_metrics_proto_init() }
func file_core_message_broker_actors_v1_metrics_proto_init() {
	if File_core_message_broker_actors_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_message_broker_actors_v1_metrics_proto_rawDesc), len(file_core_message_broker_actors_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_message_broker_actors_v1_metrics_proto_goTypes,
		DependencyIndexes: file_core_message_broker_actors_v1_metrics_proto_depIdxs,
		MessageInfos:      file_core_message_broker_actors_v1_metrics_proto_msgTypes,
	}.Build()
	File_core_message_broker_actors_v1_metrics_proto = out.File
	file_core_message_broker_actors_v1_metrics_proto_goTypes = nil
	file_core_message_broker_actors_v1_metrics_proto_depIdxs = nil
}
