// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=js"
// @generated from file core/message_broker/actors/v1/producer.proto (package core.message_broker.actors.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ProduceRequest, ProduceResponse } from "./producer_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service core.message_broker.actors.v1.Producer
 */
export const Producer = {
  typeName: "core.message_broker.actors.v1.Producer",
  methods: {
    /**
     * @generated from rpc core.message_broker.actors.v1.Producer.Produce
     */
    produce: {
      name: "Produce",
      I: ProduceRequest,
      O: ProduceResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
};

