// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: core/message_broker/actors/v1/query.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryOp int32

const (
	UnaryOp_UNARY_OP_UNSPECIFIED UnaryOp = 0
	UnaryOp_UNARY_OP_NOT         UnaryOp = 1 // Boolean → Boolean
	UnaryOp_UNARY_OP_NEGATE      UnaryOp = 2 // Integer → Integer  (unary minus)
)

// Enum value maps for UnaryOp.
var (
	UnaryOp_name = map[int32]string{
		0: "UNARY_OP_UNSPECIFIED",
		1: "UNARY_OP_NOT",
		2: "UNARY_OP_NEGATE",
	}
	UnaryOp_value = map[string]int32{
		"UNARY_OP_UNSPECIFIED": 0,
		"UNARY_OP_NOT":         1,
		"UNARY_OP_NEGATE":      2,
	}
)

func (x UnaryOp) Enum() *UnaryOp {
	p := new(UnaryOp)
	*p = x
	return p
}

func (x UnaryOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnaryOp) Descriptor() protoreflect.EnumDescriptor {
	return file_core_message_broker_actors_v1_query_proto_enumTypes[0].Descriptor()
}

func (UnaryOp) Type() protoreflect.EnumType {
	return &file_core_message_broker_actors_v1_query_proto_enumTypes[0]
}

func (x UnaryOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnaryOp.Descriptor instead.
func (UnaryOp) EnumDescriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{0}
}

type BinaryOp int32

const (
	BinaryOp_BINARY_OP_UNSPECIFIED BinaryOp = 0
	// Logical — Boolean × Boolean → Boolean
	// AND and OR short-circuit per the spec.
	BinaryOp_BINARY_OP_AND BinaryOp = 1
	BinaryOp_BINARY_OP_OR  BinaryOp = 2
	BinaryOp_BINARY_OP_XOR BinaryOp = 3
	// Equality — Boolean | Integer | String × same → Boolean
	BinaryOp_BINARY_OP_EQ  BinaryOp = 4 // =
	BinaryOp_BINARY_OP_NEQ BinaryOp = 5 // != or <> (both map to this variant)
	// Ordered comparison — Integer × Integer → Boolean
	BinaryOp_BINARY_OP_LT  BinaryOp = 6 // <
	BinaryOp_BINARY_OP_LTE BinaryOp = 7 // <=
	BinaryOp_BINARY_OP_GT  BinaryOp = 8 // >
	BinaryOp_BINARY_OP_GTE BinaryOp = 9 // >=
	// Arithmetic — Integer × Integer → Integer
	// Division and modulo by zero return 0 and raise MathError per the spec.
	BinaryOp_BINARY_OP_ADD BinaryOp = 10 // +
	BinaryOp_BINARY_OP_SUB BinaryOp = 11 // -
	BinaryOp_BINARY_OP_MUL BinaryOp = 12 // *
	BinaryOp_BINARY_OP_DIV BinaryOp = 13 // /
	BinaryOp_BINARY_OP_MOD BinaryOp = 14 // %
)

// Enum value maps for BinaryOp.
var (
	BinaryOp_name = map[int32]string{
		0:  "BINARY_OP_UNSPECIFIED",
		1:  "BINARY_OP_AND",
		2:  "BINARY_OP_OR",
		3:  "BINARY_OP_XOR",
		4:  "BINARY_OP_EQ",
		5:  "BINARY_OP_NEQ",
		6:  "BINARY_OP_LT",
		7:  "BINARY_OP_LTE",
		8:  "BINARY_OP_GT",
		9:  "BINARY_OP_GTE",
		10: "BINARY_OP_ADD",
		11: "BINARY_OP_SUB",
		12: "BINARY_OP_MUL",
		13: "BINARY_OP_DIV",
		14: "BINARY_OP_MOD",
	}
	BinaryOp_value = map[string]int32{
		"BINARY_OP_UNSPECIFIED": 0,
		"BINARY_OP_AND":         1,
		"BINARY_OP_OR":          2,
		"BINARY_OP_XOR":         3,
		"BINARY_OP_EQ":          4,
		"BINARY_OP_NEQ":         5,
		"BINARY_OP_LT":          6,
		"BINARY_OP_LTE":         7,
		"BINARY_OP_GT":          8,
		"BINARY_OP_GTE":         9,
		"BINARY_OP_ADD":         10,
		"BINARY_OP_SUB":         11,
		"BINARY_OP_MUL":         12,
		"BINARY_OP_DIV":         13,
		"BINARY_OP_MOD":         14,
	}
)

func (x BinaryOp) Enum() *BinaryOp {
	p := new(BinaryOp)
	*p = x
	return p
}

func (x BinaryOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinaryOp) Descriptor() protoreflect.EnumDescriptor {
	return file_core_message_broker_actors_v1_query_proto_enumTypes[1].Descriptor()
}

func (BinaryOp) Type() protoreflect.EnumType {
	return &file_core_message_broker_actors_v1_query_proto_enumTypes[1]
}

func (x BinaryOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinaryOp.Descriptor instead.
func (BinaryOp) EnumDescriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{1}
}

type BuiltinFunction int32

const (
	BuiltinFunction_FUNCTION_UNSPECIFIED BuiltinFunction = 0
	// LENGTH(x: String) → Integer
	// Returns the number of characters in x.
	BuiltinFunction_FUNCTION_LENGTH BuiltinFunction = 1
	// CONCAT(x1, x2, ...: String) → String
	// Returns the concatenation of all arguments. Zero args returns "".
	BuiltinFunction_FUNCTION_CONCAT BuiltinFunction = 2
	// CONCAT_WS(delimiter: String, x1, x2, ...: String) → String
	// Returns arguments joined by delimiter. Zero value args returns "".
	BuiltinFunction_FUNCTION_CONCAT_WS BuiltinFunction = 3
	// LOWER(x: String) → String
	BuiltinFunction_FUNCTION_LOWER BuiltinFunction = 4
	// UPPER(x: String) → String
	BuiltinFunction_FUNCTION_UPPER BuiltinFunction = 5
	// TRIM(x: String) → String
	// Removes leading and trailing Unicode whitespace.
	BuiltinFunction_FUNCTION_TRIM BuiltinFunction = 6
	// LEFT(x: String, n: Integer) → String
	// Returns the first n characters. Returns x when LENGTH(x) <= n.
	// Returns x + FunctionEvaluationError when n < 0.
	BuiltinFunction_FUNCTION_LEFT BuiltinFunction = 7
	// RIGHT(x: String, n: Integer) → String
	// Returns the last n characters. Returns x when LENGTH(x) <= n.
	// Returns x + FunctionEvaluationError when n < 0.
	BuiltinFunction_FUNCTION_RIGHT BuiltinFunction = 8
	// SUBSTRING(x: String, pos: Integer) → String
	// SUBSTRING(x: String, pos: Integer, len: Integer) → String
	// 1-indexed. Negative pos counts from the end. pos=0 returns "".
	// Returns "" + FunctionEvaluationError when |pos| > LENGTH(x) or len < 0.
	BuiltinFunction_FUNCTION_SUBSTRING BuiltinFunction = 9
	// ABS(x: Integer) → Integer
	// Returns the absolute value of x.
	// ABS(-2147483648) returns 2147483647 + MathError per the spec.
	BuiltinFunction_FUNCTION_ABS BuiltinFunction = 10
)

// Enum value maps for BuiltinFunction.
var (
	BuiltinFunction_name = map[int32]string{
		0:  "FUNCTION_UNSPECIFIED",
		1:  "FUNCTION_LENGTH",
		2:  "FUNCTION_CONCAT",
		3:  "FUNCTION_CONCAT_WS",
		4:  "FUNCTION_LOWER",
		5:  "FUNCTION_UPPER",
		6:  "FUNCTION_TRIM",
		7:  "FUNCTION_LEFT",
		8:  "FUNCTION_RIGHT",
		9:  "FUNCTION_SUBSTRING",
		10: "FUNCTION_ABS",
	}
	BuiltinFunction_value = map[string]int32{
		"FUNCTION_UNSPECIFIED": 0,
		"FUNCTION_LENGTH":      1,
		"FUNCTION_CONCAT":      2,
		"FUNCTION_CONCAT_WS":   3,
		"FUNCTION_LOWER":       4,
		"FUNCTION_UPPER":       5,
		"FUNCTION_TRIM":        6,
		"FUNCTION_LEFT":        7,
		"FUNCTION_RIGHT":       8,
		"FUNCTION_SUBSTRING":   9,
		"FUNCTION_ABS":         10,
	}
)

func (x BuiltinFunction) Enum() *BuiltinFunction {
	p := new(BuiltinFunction)
	*p = x
	return p
}

func (x BuiltinFunction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuiltinFunction) Descriptor() protoreflect.EnumDescriptor {
	return file_core_message_broker_actors_v1_query_proto_enumTypes[2].Descriptor()
}

func (BuiltinFunction) Type() protoreflect.EnumType {
	return &file_core_message_broker_actors_v1_query_proto_enumTypes[2]
}

func (x BuiltinFunction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuiltinFunction.Descriptor instead.
func (BuiltinFunction) EnumDescriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{2}
}

type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expression *Expression `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression" bun:"expression" csv:"expression" pg:"expression" yaml:"expression"`
	Limit      int32       `protobuf:"varint,2,opt,name=limit,proto3" json:"limit" bun:"limit" csv:"limit" pg:"limit" yaml:"limit"` // 0 = server default; caps historical replay for QueryStream
	After      string      `protobuf:"bytes,3,opt,name=after,proto3" json:"after" bun:"after" csv:"after" pg:"after" yaml:"after"`  // ISO 8601 timestamp — replay events after this point before going live
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetExpression() *Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*CloudEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events" bun:"events" csv:"events" pg:"events" yaml:"events"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetEvents() []*CloudEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// One event per stream message so the web-client can render each event as it
// arrives rather than waiting for a batch.
type QueryStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *CloudEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event" bun:"event" csv:"event" pg:"event" yaml:"event"`
}

func (x *QueryStreamResponse) Reset() {
	*x = QueryStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStreamResponse) ProtoMessage() {}

func (x *QueryStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStreamResponse.ProtoReflect.Descriptor instead.
func (*QueryStreamResponse) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStreamResponse) GetEvent() *CloudEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Expr:
	//
	//	*Expression_Literal
	//	*Expression_Attribute
	//	*Expression_Unary
	//	*Expression_Binary
	//	*Expression_Like
	//	*Expression_Exists
	//	*Expression_In
	//	*Expression_FunctionCall
	Expr isExpression_Expr `protobuf_oneof:"expr"`
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{3}
}

func (m *Expression) GetExpr() isExpression_Expr {
	if m != nil {
		return m.Expr
	}
	return nil
}

func (x *Expression) GetLiteral() *Literal {
	if x, ok := x.GetExpr().(*Expression_Literal); ok {
		return x.Literal
	}
	return nil
}

func (x *Expression) GetAttribute() *AttributeRef {
	if x, ok := x.GetExpr().(*Expression_Attribute); ok {
		return x.Attribute
	}
	return nil
}

func (x *Expression) GetUnary() *UnaryExpr {
	if x, ok := x.GetExpr().(*Expression_Unary); ok {
		return x.Unary
	}
	return nil
}

func (x *Expression) GetBinary() *BinaryExpr {
	if x, ok := x.GetExpr().(*Expression_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *Expression) GetLike() *LikeExpr {
	if x, ok := x.GetExpr().(*Expression_Like); ok {
		return x.Like
	}
	return nil
}

func (x *Expression) GetExists() *ExistsExpr {
	if x, ok := x.GetExpr().(*Expression_Exists); ok {
		return x.Exists
	}
	return nil
}

func (x *Expression) GetIn() *InExpr {
	if x, ok := x.GetExpr().(*Expression_In); ok {
		return x.In
	}
	return nil
}

func (x *Expression) GetFunctionCall() *FunctionCall {
	if x, ok := x.GetExpr().(*Expression_FunctionCall); ok {
		return x.FunctionCall
	}
	return nil
}

type isExpression_Expr interface {
	isExpression_Expr()
}

type Expression_Literal struct {
	Literal *Literal `protobuf:"bytes,1,opt,name=literal,proto3,oneof" bun:"literal" csv:"literal" json:"literal" pg:"literal" yaml:"literal"`
}

type Expression_Attribute struct {
	Attribute *AttributeRef `protobuf:"bytes,2,opt,name=attribute,proto3,oneof" bun:"attribute" csv:"attribute" json:"attribute" pg:"attribute" yaml:"attribute"`
}

type Expression_Unary struct {
	Unary *UnaryExpr `protobuf:"bytes,3,opt,name=unary,proto3,oneof" bun:"unary" csv:"unary" json:"unary" pg:"unary" yaml:"unary"`
}

type Expression_Binary struct {
	Binary *BinaryExpr `protobuf:"bytes,4,opt,name=binary,proto3,oneof" bun:"binary" csv:"binary" json:"binary" pg:"binary" yaml:"binary"`
}

type Expression_Like struct {
	Like *LikeExpr `protobuf:"bytes,5,opt,name=like,proto3,oneof" bun:"like" csv:"like" json:"like" pg:"like" yaml:"like"`
}

type Expression_Exists struct {
	Exists *ExistsExpr `protobuf:"bytes,6,opt,name=exists,proto3,oneof" bun:"exists" csv:"exists" json:"exists" pg:"exists" yaml:"exists"`
}

type Expression_In struct {
	In *InExpr `protobuf:"bytes,7,opt,name=in,proto3,oneof" bun:"in" csv:"in" json:"in" pg:"in" yaml:"in"`
}

type Expression_FunctionCall struct {
	FunctionCall *FunctionCall `protobuf:"bytes,8,opt,name=function_call,json=functionCall,proto3,oneof" bun:"function_call" csv:"function_call" json:"function_call" pg:"function_call" yaml:"function_call"`
}

func (*Expression_Literal) isExpression_Expr() {}

func (*Expression_Attribute) isExpression_Expr() {}

func (*Expression_Unary) isExpression_Expr() {}

func (*Expression_Binary) isExpression_Expr() {}

func (*Expression_Like) isExpression_Expr() {}

func (*Expression_Exists) isExpression_Expr() {}

func (*Expression_In) isExpression_Expr() {}

func (*Expression_FunctionCall) isExpression_Expr() {}

// The three primitive types defined by the CESQL type system.
// URI, URI-Reference, and Timestamp are represented as string_value.
type Literal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Literal_IntegerValue
	//	*Literal_BoolValue
	//	*Literal_StringValue
	Value isLiteral_Value `protobuf_oneof:"value"`
}

func (x *Literal) Reset() {
	*x = Literal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Literal) ProtoMessage() {}

func (x *Literal) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Literal.ProtoReflect.Descriptor instead.
func (*Literal) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{4}
}

func (m *Literal) GetValue() isLiteral_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Literal) GetIntegerValue() int32 {
	if x, ok := x.GetValue().(*Literal_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (x *Literal) GetBoolValue() bool {
	if x, ok := x.GetValue().(*Literal_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *Literal) GetStringValue() string {
	if x, ok := x.GetValue().(*Literal_StringValue); ok {
		return x.StringValue
	}
	return ""
}

type isLiteral_Value interface {
	isLiteral_Value()
}

type Literal_IntegerValue struct {
	IntegerValue int32 `protobuf:"varint,1,opt,name=integer_value,json=integerValue,proto3,oneof" bun:"integer_value" csv:"integer_value" json:"integer_value" pg:"integer_value" yaml:"integer_value"`
}

type Literal_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof" bun:"bool_value" csv:"bool_value" json:"bool_value" pg:"bool_value" yaml:"bool_value"`
}

type Literal_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof" bun:"string_value" csv:"string_value" json:"string_value" pg:"string_value" yaml:"string_value"`
}

func (*Literal_IntegerValue) isLiteral_Value() {}

func (*Literal_BoolValue) isLiteral_Value() {}

func (*Literal_StringValue) isLiteral_Value() {}

// References a CloudEvent context attribute or extension by name.
//
// Required attributes (always present): id, source, specversion, type
// Optional attributes: datacontenttype, dataschema, subject, time
// Extensions: any custom attribute added by the event producer
//
// A missing optional or extension attribute evaluates to the zero value of the
// subexpression return type and raises MissingAttributeError per the spec.
type AttributeRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" bun:"name" csv:"name" pg:"name" yaml:"name"`
}

func (x *AttributeRef) Reset() {
	*x = AttributeRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeRef) ProtoMessage() {}

func (x *AttributeRef) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeRef.ProtoReflect.Descriptor instead.
func (*AttributeRef) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *AttributeRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnaryExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op      UnaryOp     `protobuf:"varint,1,opt,name=op,proto3,enum=core.message_broker.actors.v1.UnaryOp" json:"op" bun:"op" csv:"op" pg:"op" yaml:"op"`
	Operand *Expression `protobuf:"bytes,2,opt,name=operand,proto3" json:"operand" bun:"operand" csv:"operand" pg:"operand" yaml:"operand"`
}

func (x *UnaryExpr) Reset() {
	*x = UnaryExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryExpr) ProtoMessage() {}

func (x *UnaryExpr) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryExpr.ProtoReflect.Descriptor instead.
func (*UnaryExpr) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *UnaryExpr) GetOp() UnaryOp {
	if x != nil {
		return x.Op
	}
	return UnaryOp_UNARY_OP_UNSPECIFIED
}

func (x *UnaryExpr) GetOperand() *Expression {
	if x != nil {
		return x.Operand
	}
	return nil
}

type BinaryExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left  *Expression `protobuf:"bytes,1,opt,name=left,proto3" json:"left" bun:"left" csv:"left" pg:"left" yaml:"left"`
	Op    BinaryOp    `protobuf:"varint,2,opt,name=op,proto3,enum=core.message_broker.actors.v1.BinaryOp" json:"op" bun:"op" csv:"op" pg:"op" yaml:"op"`
	Right *Expression `protobuf:"bytes,3,opt,name=right,proto3" json:"right" bun:"right" csv:"right" pg:"right" yaml:"right"`
}

func (x *BinaryExpr) Reset() {
	*x = BinaryExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryExpr) ProtoMessage() {}

func (x *BinaryExpr) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryExpr.ProtoReflect.Descriptor instead.
func (*BinaryExpr) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *BinaryExpr) GetLeft() *Expression {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *BinaryExpr) GetOp() BinaryOp {
	if x != nil {
		return x.Op
	}
	return BinaryOp_BINARY_OP_UNSPECIFIED
}

func (x *BinaryExpr) GetRight() *Expression {
	if x != nil {
		return x.Right
	}
	return nil
}

// String × String → Boolean
// Pattern syntax: % matches any sequence of characters,
//
//	_ matches exactly one character,
//	\ escapes a literal % or _.
type LikeExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operand *Expression `protobuf:"bytes,1,opt,name=operand,proto3" json:"operand" bun:"operand" csv:"operand" pg:"operand" yaml:"operand"`
	Pattern string      `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern" bun:"pattern" csv:"pattern" pg:"pattern" yaml:"pattern"`  // string literal containing the LIKE pattern
	Negated bool        `protobuf:"varint,3,opt,name=negated,proto3" json:"negated" bun:"negated" csv:"negated" pg:"negated" yaml:"negated"` // true → NOT LIKE
}

func (x *LikeExpr) Reset() {
	*x = LikeExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeExpr) ProtoMessage() {}

func (x *LikeExpr) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeExpr.ProtoReflect.Descriptor instead.
func (*LikeExpr) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *LikeExpr) GetOperand() *Expression {
	if x != nil {
		return x.Operand
	}
	return nil
}

func (x *LikeExpr) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *LikeExpr) GetNegated() bool {
	if x != nil {
		return x.Negated
	}
	return false
}

// Returns true if the named attribute is present on the CloudEvent.
// Always evaluates true for the four required attributes.
type ExistsExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attribute string `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute" bun:"attribute" csv:"attribute" pg:"attribute" yaml:"attribute"`
}

func (x *ExistsExpr) Reset() {
	*x = ExistsExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistsExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsExpr) ProtoMessage() {}

func (x *ExistsExpr) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsExpr.ProtoReflect.Descriptor instead.
func (*ExistsExpr) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *ExistsExpr) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

// expression IN (e1, e2, ...) → Boolean
// The values set must contain at least one element.
type InExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operand *Expression   `protobuf:"bytes,1,opt,name=operand,proto3" json:"operand" bun:"operand" csv:"operand" pg:"operand" yaml:"operand"`
	Values  []*Expression `protobuf:"bytes,2,rep,name=values,proto3" json:"values" bun:"values" csv:"values" pg:"values" yaml:"values"`
	Negated bool          `protobuf:"varint,3,opt,name=negated,proto3" json:"negated" bun:"negated" csv:"negated" pg:"negated" yaml:"negated"` // true → NOT IN
}

func (x *InExpr) Reset() {
	*x = InExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InExpr) ProtoMessage() {}

func (x *InExpr) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InExpr.ProtoReflect.Descriptor instead.
func (*InExpr) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *InExpr) GetOperand() *Expression {
	if x != nil {
		return x.Operand
	}
	return nil
}

func (x *InExpr) GetValues() []*Expression {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *InExpr) GetNegated() bool {
	if x != nil {
		return x.Negated
	}
	return false
}

// All built-in CESQL functions are enumerated here. The argument count and
// types for each function are documented below and enforced at evaluation time.
type FunctionCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function BuiltinFunction `protobuf:"varint,1,opt,name=function,proto3,enum=core.message_broker.actors.v1.BuiltinFunction" json:"function" bun:"function" csv:"function" pg:"function" yaml:"function"`
	Args     []*Expression   `protobuf:"bytes,2,rep,name=args,proto3" json:"args" bun:"args" csv:"args" pg:"args" yaml:"args"`
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_broker_actors_v1_query_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_core_message_broker_actors_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *FunctionCall) GetFunction() BuiltinFunction {
	if x != nil {
		return x.Function
	}
	return BuiltinFunction_FUNCTION_UNSPECIFIED
}

func (x *FunctionCall) GetArgs() []*Expression {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_core_message_broker_actors_v1_query_proto protoreflect.FileDescriptor

var file_core_message_broker_actors_v1_query_proto_rawDesc = []byte{
	0x0a, 0x29, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x2a, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x22, 0x52,
	0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x56, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xbd, 0x04, 0x0a, 0x0a, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x07, 0x6c, 0x69, 0x74,
	0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x48, 0x00, 0x52, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x4b, 0x0a,
	0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x66, 0x48, 0x00, 0x52,
	0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x40, 0x0a, 0x05, 0x75, 0x6e,
	0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x45,
	0x78, 0x70, 0x72, 0x48, 0x00, 0x52, 0x05, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x43, 0x0a, 0x06,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x12, 0x3d, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x6b, 0x65, 0x45, 0x78, 0x70, 0x72, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65,
	0x12, 0x43, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x45, 0x78, 0x70, 0x72, 0x48, 0x00, 0x52, 0x06, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6e, 0x45, 0x78, 0x70, 0x72, 0x48, 0x00, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x52,
	0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x6c, 0x6c, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x6c, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x65, 0x78, 0x70, 0x72, 0x22, 0x7f, 0x0a, 0x07, 0x4c, 0x69,
	0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0c,
	0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a,
	0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a,
	0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x88, 0x01, 0x0a, 0x09, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x12, 0x36, 0x0a,
	0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x4f,
	0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x43, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x22, 0xc5, 0x01, 0x0a, 0x0a, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x12, 0x3d, 0x0a, 0x04, 0x6c, 0x65, 0x66,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x37, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4f, 0x70, 0x52, 0x02, 0x6f,
	0x70, 0x12, 0x3f, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x08, 0x4c, 0x69, 0x6b, 0x65, 0x45, 0x78, 0x70, 0x72, 0x12,
	0x43, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x0a, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x45, 0x78, 0x70, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x06, 0x49, 0x6e, 0x45, 0x78, 0x70, 0x72, 0x12,
	0x43, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x12, 0x41, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x99, 0x01, 0x0a, 0x0c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x6c, 0x6c, 0x12, 0x4a, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x2a, 0x4a, 0x0a,
	0x07, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x4f, 0x70, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x41, 0x52,
	0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x4e,
	0x4f, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50,
	0x5f, 0x4e, 0x45, 0x47, 0x41, 0x54, 0x45, 0x10, 0x02, 0x2a, 0xab, 0x02, 0x0a, 0x08, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x4f, 0x70, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59,
	0x5f, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x41,
	0x4e, 0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f,
	0x50, 0x5f, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59,
	0x5f, 0x4f, 0x50, 0x5f, 0x58, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x49, 0x4e,
	0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x45, 0x51, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x42,
	0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x4e, 0x45, 0x51, 0x10, 0x05, 0x12, 0x10,
	0x0a, 0x0c, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x4c, 0x54, 0x10, 0x06,
	0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x4c, 0x54,
	0x45, 0x10, 0x07, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50,
	0x5f, 0x47, 0x54, 0x10, 0x08, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f,
	0x4f, 0x50, 0x5f, 0x47, 0x54, 0x45, 0x10, 0x09, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41,
	0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x41, 0x44, 0x44, 0x10, 0x0a, 0x12, 0x11, 0x0a, 0x0d, 0x42,
	0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x53, 0x55, 0x42, 0x10, 0x0b, 0x12, 0x11,
	0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x4d, 0x55, 0x4c, 0x10,
	0x0c, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f, 0x50, 0x5f, 0x44,
	0x49, 0x56, 0x10, 0x0d, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x4f,
	0x50, 0x5f, 0x4d, 0x4f, 0x44, 0x10, 0x0e, 0x2a, 0xf9, 0x01, 0x0a, 0x0f, 0x42, 0x75, 0x69, 0x6c,
	0x74, 0x69, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x14, 0x46,
	0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x4c, 0x45, 0x4e, 0x47, 0x54, 0x48, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x55,
	0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x43, 0x41, 0x54, 0x10, 0x02, 0x12,
	0x16, 0x0a, 0x12, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x43,
	0x41, 0x54, 0x5f, 0x57, 0x53, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x55, 0x4e, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x46,
	0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x50, 0x45, 0x52, 0x10, 0x05, 0x12,
	0x11, 0x0a, 0x0d, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x52, 0x49, 0x4d,
	0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c,
	0x45, 0x46, 0x54, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x08, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x55, 0x4e,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10,
	0x09, 0x12, 0x10, 0x0a, 0x0c, 0x46, 0x55, 0x4e, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x42,
	0x53, 0x10, 0x0a, 0x32, 0xe1, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x64, 0x0a,
	0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x72, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x2b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x32, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x61, 0x64, 0x79, 0x2d, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x2f, 0x64, 0x72, 0x61, 0x66, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_core_message_broker_actors_v1_query_proto_rawDescOnce sync.Once
	file_core_message_broker_actors_v1_query_proto_rawDescData = file_core_message_broker_actors_v1_query_proto_rawDesc
)

func file_core_message_broker_actors_v1_query_proto_rawDescGZIP() []byte {
	file_core_message_broker_actors_v1_query_proto_rawDescOnce.Do(func() {
		file_core_message_broker_actors_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_message_broker_actors_v1_query_proto_rawDescData)
	})
	return file_core_message_broker_actors_v1_query_proto_rawDescData
}

var file_core_message_broker_actors_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_core_message_broker_actors_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_core_message_broker_actors_v1_query_proto_goTypes = []any{
	(UnaryOp)(0),                // 0: core.message_broker.actors.v1.UnaryOp
	(BinaryOp)(0),               // 1: core.message_broker.actors.v1.BinaryOp
	(BuiltinFunction)(0),        // 2: core.message_broker.actors.v1.BuiltinFunction
	(*QueryRequest)(nil),        // 3: core.message_broker.actors.v1.QueryRequest
	(*QueryResponse)(nil),       // 4: core.message_broker.actors.v1.QueryResponse
	(*QueryStreamResponse)(nil), // 5: core.message_broker.actors.v1.QueryStreamResponse
	(*Expression)(nil),          // 6: core.message_broker.actors.v1.Expression
	(*Literal)(nil),             // 7: core.message_broker.actors.v1.Literal
	(*AttributeRef)(nil),        // 8: core.message_broker.actors.v1.AttributeRef
	(*UnaryExpr)(nil),           // 9: core.message_broker.actors.v1.UnaryExpr
	(*BinaryExpr)(nil),          // 10: core.message_broker.actors.v1.BinaryExpr
	(*LikeExpr)(nil),            // 11: core.message_broker.actors.v1.LikeExpr
	(*ExistsExpr)(nil),          // 12: core.message_broker.actors.v1.ExistsExpr
	(*InExpr)(nil),              // 13: core.message_broker.actors.v1.InExpr
	(*FunctionCall)(nil),        // 14: core.message_broker.actors.v1.FunctionCall
	(*CloudEvent)(nil),          // 15: core.message_broker.actors.v1.CloudEvent
}
var file_core_message_broker_actors_v1_query_proto_depIdxs = []int32{
	6,  // 0: core.message_broker.actors.v1.QueryRequest.expression:type_name -> core.message_broker.actors.v1.Expression
	15, // 1: core.message_broker.actors.v1.QueryResponse.events:type_name -> core.message_broker.actors.v1.CloudEvent
	15, // 2: core.message_broker.actors.v1.QueryStreamResponse.event:type_name -> core.message_broker.actors.v1.CloudEvent
	7,  // 3: core.message_broker.actors.v1.Expression.literal:type_name -> core.message_broker.actors.v1.Literal
	8,  // 4: core.message_broker.actors.v1.Expression.attribute:type_name -> core.message_broker.actors.v1.AttributeRef
	9,  // 5: core.message_broker.actors.v1.Expression.unary:type_name -> core.message_broker.actors.v1.UnaryExpr
	10, // 6: core.message_broker.actors.v1.Expression.binary:type_name -> core.message_broker.actors.v1.BinaryExpr
	11, // 7: core.message_broker.actors.v1.Expression.like:type_name -> core.message_broker.actors.v1.LikeExpr
	12, // 8: core.message_broker.actors.v1.Expression.exists:type_name -> core.message_broker.actors.v1.ExistsExpr
	13, // 9: core.message_broker.actors.v1.Expression.in:type_name -> core.message_broker.actors.v1.InExpr
	14, // 10: core.message_broker.actors.v1.Expression.function_call:type_name -> core.message_broker.actors.v1.FunctionCall
	0,  // 11: core.message_broker.actors.v1.UnaryExpr.op:type_name -> core.message_broker.actors.v1.UnaryOp
	6,  // 12: core.message_broker.actors.v1.UnaryExpr.operand:type_name -> core.message_broker.actors.v1.Expression
	6,  // 13: core.message_broker.actors.v1.BinaryExpr.left:type_name -> core.message_broker.actors.v1.Expression
	1,  // 14: core.message_broker.actors.v1.BinaryExpr.op:type_name -> core.message_broker.actors.v1.BinaryOp
	6,  // 15: core.message_broker.actors.v1.BinaryExpr.right:type_name -> core.message_broker.actors.v1.Expression
	6,  // 16: core.message_broker.actors.v1.LikeExpr.operand:type_name -> core.message_broker.actors.v1.Expression
	6,  // 17: core.message_broker.actors.v1.InExpr.operand:type_name -> core.message_broker.actors.v1.Expression
	6,  // 18: core.message_broker.actors.v1.InExpr.values:type_name -> core.message_broker.actors.v1.Expression
	2,  // 19: core.message_broker.actors.v1.FunctionCall.function:type_name -> core.message_broker.actors.v1.BuiltinFunction
	6,  // 20: core.message_broker.actors.v1.FunctionCall.args:type_name -> core.message_broker.actors.v1.Expression
	3,  // 21: core.message_broker.actors.v1.Query.Query:input_type -> core.message_broker.actors.v1.QueryRequest
	3,  // 22: core.message_broker.actors.v1.Query.QueryStream:input_type -> core.message_broker.actors.v1.QueryRequest
	4,  // 23: core.message_broker.actors.v1.Query.Query:output_type -> core.message_broker.actors.v1.QueryResponse
	5,  // 24: core.message_broker.actors.v1.Query.QueryStream:output_type -> core.message_broker.actors.v1.QueryStreamResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_core_message_broker_actors_v1_query_proto_init() }
func file_core_message_broker_actors_v1_query_proto_init() {
	if File_core_message_broker_actors_v1_query_proto != nil {
		return
	}
	file_core_message_broker_actors_v1_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_core_message_broker_actors_v1_query_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*QueryStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Literal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AttributeRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UnaryExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BinaryExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LikeExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ExistsExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*InExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_message_broker_actors_v1_query_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*FunctionCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_message_broker_actors_v1_query_proto_msgTypes[3].OneofWrappers = []any{
		(*Expression_Literal)(nil),
		(*Expression_Attribute)(nil),
		(*Expression_Unary)(nil),
		(*Expression_Binary)(nil),
		(*Expression_Like)(nil),
		(*Expression_Exists)(nil),
		(*Expression_In)(nil),
		(*Expression_FunctionCall)(nil),
	}
	file_core_message_broker_actors_v1_query_proto_msgTypes[4].OneofWrappers = []any{
		(*Literal_IntegerValue)(nil),
		(*Literal_BoolValue)(nil),
		(*Literal_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_message_broker_actors_v1_query_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_message_broker_actors_v1_query_proto_goTypes,
		DependencyIndexes: file_core_message_broker_actors_v1_query_proto_depIdxs,
		EnumInfos:         file_core_message_broker_actors_v1_query_proto_enumTypes,
		MessageInfos:      file_core_message_broker_actors_v1_query_proto_msgTypes,
	}.Build()
	File_core_message_broker_actors_v1_query_proto = out.File
	file_core_message_broker_actors_v1_query_proto_rawDesc = nil
	file_core_message_broker_actors_v1_query_proto_goTypes = nil
	file_core_message_broker_actors_v1_query_proto_depIdxs = nil
}
