// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: tooling/lineman/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateObjectiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" bun:"name" csv:"name" pg:"name" yaml:"name"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description" bun:"description" csv:"description" pg:"description" yaml:"description"`
	// Left empty to default to ["Queued", "In Flight", "Done"].
	States []string `protobuf:"bytes,3,rep,name=states,proto3" json:"states" bun:"states" csv:"states" pg:"states" yaml:"states"`
}

func (x *CreateObjectiveRequest) Reset() {
	*x = CreateObjectiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjectiveRequest) ProtoMessage() {}

func (x *CreateObjectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjectiveRequest.ProtoReflect.Descriptor instead.
func (*CreateObjectiveRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateObjectiveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateObjectiveRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateObjectiveRequest) GetStates() []string {
	if x != nil {
		return x.States
	}
	return nil
}

type GetObjectiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bun:"id" csv:"id" pg:"id" yaml:"id"`
}

func (x *GetObjectiveRequest) Reset() {
	*x = GetObjectiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectiveRequest) ProtoMessage() {}

func (x *GetObjectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectiveRequest.ProtoReflect.Descriptor instead.
func (*GetObjectiveRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetObjectiveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListObjectivesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListObjectivesRequest) Reset() {
	*x = ListObjectivesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectivesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectivesRequest) ProtoMessage() {}

func (x *ListObjectivesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectivesRequest.ProtoReflect.Descriptor instead.
func (*ListObjectivesRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{2}
}

type ListObjectivesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objectives []*Objective `protobuf:"bytes,1,rep,name=objectives,proto3" json:"objectives" bun:"objectives" csv:"objectives" pg:"objectives" yaml:"objectives"`
}

func (x *ListObjectivesResponse) Reset() {
	*x = ListObjectivesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectivesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectivesResponse) ProtoMessage() {}

func (x *ListObjectivesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectivesResponse.ProtoReflect.Descriptor instead.
func (*ListObjectivesResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListObjectivesResponse) GetObjectives() []*Objective {
	if x != nil {
		return x.Objectives
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectiveId string   `protobuf:"bytes,1,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id" bun:"objective_id" csv:"objective_id" pg:"objective_id" yaml:"objective_id"` // empty for a standalone task
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name" bun:"name" csv:"name" pg:"name" yaml:"name"`
	Priority    Priority `protobuf:"varint,3,opt,name=priority,proto3,enum=tooling.lineman.v1.Priority" json:"priority" bun:"priority" csv:"priority" pg:"priority" yaml:"priority"`
	// Left empty to default to the objective's first state (or "Queued" for
	// a standalone task).
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state" bun:"state" csv:"state" pg:"state" yaml:"state"`
	// Everything needed to complete the task -- optional.
	Details string `protobuf:"bytes,5,opt,name=details,proto3" json:"details" bun:"details" csv:"details" pg:"details" yaml:"details"`
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateTaskRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateTaskRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bun:"id" csv:"id" pg:"id" yaml:"id"`
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// All filters optional; an unset field means "no filter on this field."
	ObjectiveId string `protobuf:"bytes,1,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id" bun:"objective_id" csv:"objective_id" pg:"objective_id" yaml:"objective_id"`
	State       string `protobuf:"bytes,2,opt,name=state,proto3" json:"state" bun:"state" csv:"state" pg:"state" yaml:"state"`
	AgentId     string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id" bun:"agent_id" csv:"agent_id" pg:"agent_id" yaml:"agent_id"`
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

func (x *ListTasksRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks" bun:"tasks" csv:"tasks" pg:"tasks" yaml:"tasks"`
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpdateTaskStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id" bun:"task_id" csv:"task_id" pg:"task_id" yaml:"task_id"`
	NewState string `protobuf:"bytes,2,opt,name=new_state,json=newState,proto3" json:"new_state" bun:"new_state" csv:"new_state" pg:"new_state" yaml:"new_state"`
}

func (x *UpdateTaskStateRequest) Reset() {
	*x = UpdateTaskStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStateRequest) ProtoMessage() {}

func (x *UpdateTaskStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStateRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskStateRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskStateRequest) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

type ReorderTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id" bun:"task_id" csv:"task_id" pg:"task_id" yaml:"task_id"`
	// The task's new order value is computed server-side as the midpoint
	// between before_task_id's and after_task_id's current order (either
	// may be empty to mean "start"/"end" of the list).
	BeforeTaskId string `protobuf:"bytes,2,opt,name=before_task_id,json=beforeTaskId,proto3" json:"before_task_id" bun:"before_task_id" csv:"before_task_id" pg:"before_task_id" yaml:"before_task_id"`
	AfterTaskId  string `protobuf:"bytes,3,opt,name=after_task_id,json=afterTaskId,proto3" json:"after_task_id" bun:"after_task_id" csv:"after_task_id" pg:"after_task_id" yaml:"after_task_id"`
}

func (x *ReorderTaskRequest) Reset() {
	*x = ReorderTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReorderTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderTaskRequest) ProtoMessage() {}

func (x *ReorderTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderTaskRequest.ProtoReflect.Descriptor instead.
func (*ReorderTaskRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReorderTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReorderTaskRequest) GetBeforeTaskId() string {
	if x != nil {
		return x.BeforeTaskId
	}
	return ""
}

func (x *ReorderTaskRequest) GetAfterTaskId() string {
	if x != nil {
		return x.AfterTaskId
	}
	return ""
}

type AssignAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId  string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id" bun:"task_id" csv:"task_id" pg:"task_id" yaml:"task_id"`
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id" bun:"agent_id" csv:"agent_id" pg:"agent_id" yaml:"agent_id"` // empty to unassign
}

func (x *AssignAgentRequest) Reset() {
	*x = AssignAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentRequest) ProtoMessage() {}

func (x *AssignAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentRequest.ProtoReflect.Descriptor instead.
func (*AssignAgentRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *AssignAgentRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId          string    `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id" bun:"agent_id" csv:"agent_id" pg:"agent_id" yaml:"agent_id"`
	AgentDisplayName string    `protobuf:"bytes,2,opt,name=agent_display_name,json=agentDisplayName,proto3" json:"agent_display_name" bun:"agent_display_name" csv:"agent_display_name" pg:"agent_display_name" yaml:"agent_display_name"` // used only the first time agent_id is seen
	AgentKind        AgentKind `protobuf:"varint,3,opt,name=agent_kind,json=agentKind,proto3,enum=tooling.lineman.v1.AgentKind" json:"agent_kind" bun:"agent_kind" csv:"agent_kind" pg:"agent_kind" yaml:"agent_kind"`                     // used only the first time agent_id is seen
	TaskId           string    `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id" bun:"task_id" csv:"task_id" pg:"task_id" yaml:"task_id"`
	CurrentAction    string    `protobuf:"bytes,5,opt,name=current_action,json=currentAction,proto3" json:"current_action" bun:"current_action" csv:"current_action" pg:"current_action" yaml:"current_action"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentDisplayName() string {
	if x != nil {
		return x.AgentDisplayName
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentKind() AgentKind {
	if x != nil {
		return x.AgentKind
	}
	return AgentKind_AGENT_KIND_UNSPECIFIED
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentAction() string {
	if x != nil {
		return x.CurrentAction
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{12}
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{13}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents" bun:"agents" csv:"agents" pg:"agents" yaml:"agents"`
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type RequestInputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id" bun:"task_id" csv:"task_id" pg:"task_id" yaml:"task_id"`
	Question string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question" bun:"question" csv:"question" pg:"question" yaml:"question"`
	Options  []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options" bun:"options" csv:"options" pg:"options" yaml:"options"`
}

func (x *RequestInputRequest) Reset() {
	*x = RequestInputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInputRequest) ProtoMessage() {}

func (x *RequestInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInputRequest.ProtoReflect.Descriptor instead.
func (*RequestInputRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *RequestInputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RequestInputRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *RequestInputRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProvideGuidanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id" bun:"task_id" csv:"task_id" pg:"task_id" yaml:"task_id"`
	Response  string `protobuf:"bytes,2,opt,name=response,proto3" json:"response" bun:"response" csv:"response" pg:"response" yaml:"response"`
	NextState string `protobuf:"bytes,3,opt,name=next_state,json=nextState,proto3" json:"next_state" bun:"next_state" csv:"next_state" pg:"next_state" yaml:"next_state"`
}

func (x *ProvideGuidanceRequest) Reset() {
	*x = ProvideGuidanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvideGuidanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideGuidanceRequest) ProtoMessage() {}

func (x *ProvideGuidanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideGuidanceRequest.ProtoReflect.Descriptor instead.
func (*ProvideGuidanceRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *ProvideGuidanceRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProvideGuidanceRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ProvideGuidanceRequest) GetNextState() string {
	if x != nil {
		return x.NextState
	}
	return ""
}

type CreateScheduledTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectiveId string                 `protobuf:"bytes,1,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id" bun:"objective_id" csv:"objective_id" pg:"objective_id" yaml:"objective_id"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description" bun:"description" csv:"description" pg:"description" yaml:"description"`
	Priority    Priority               `protobuf:"varint,3,opt,name=priority,proto3,enum=tooling.lineman.v1.Priority" json:"priority" bun:"priority" csv:"priority" pg:"priority" yaml:"priority"`
	FireAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=fire_at,json=fireAt,proto3" json:"fire_at" bun:"fire_at" csv:"fire_at" pg:"fire_at" yaml:"fire_at"`
}

func (x *CreateScheduledTaskRequest) Reset() {
	*x = CreateScheduledTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledTaskRequest) ProtoMessage() {}

func (x *CreateScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateScheduledTaskRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateScheduledTaskRequest) GetFireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FireAt
	}
	return nil
}

type ListScheduledTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectiveId string `protobuf:"bytes,1,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id" bun:"objective_id" csv:"objective_id" pg:"objective_id" yaml:"objective_id"` // optional filter
}

func (x *ListScheduledTasksRequest) Reset() {
	*x = ListScheduledTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListScheduledTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksRequest) ProtoMessage() {}

func (x *ListScheduledTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListScheduledTasksRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

type ListScheduledTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduledTasks []*ScheduledTask `protobuf:"bytes,1,rep,name=scheduled_tasks,json=scheduledTasks,proto3" json:"scheduled_tasks" bun:"scheduled_tasks" csv:"scheduled_tasks" pg:"scheduled_tasks" yaml:"scheduled_tasks"`
}

func (x *ListScheduledTasksResponse) Reset() {
	*x = ListScheduledTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListScheduledTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksResponse) ProtoMessage() {}

func (x *ListScheduledTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListScheduledTasksResponse) GetScheduledTasks() []*ScheduledTask {
	if x != nil {
		return x.ScheduledTasks
	}
	return nil
}

type CancelScheduledTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bun:"id" csv:"id" pg:"id" yaml:"id"`
}

func (x *CancelScheduledTaskRequest) Reset() {
	*x = CancelScheduledTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduledTaskRequest) ProtoMessage() {}

func (x *CancelScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *CancelScheduledTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelScheduledTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelScheduledTaskResponse) Reset() {
	*x = CancelScheduledTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduledTaskResponse) ProtoMessage() {}

func (x *CancelScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{21}
}

type CreateLoopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectiveId string      `protobuf:"bytes,1,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id" bun:"objective_id" csv:"objective_id" pg:"objective_id" yaml:"objective_id"`
	Description string      `protobuf:"bytes,2,opt,name=description,proto3" json:"description" bun:"description" csv:"description" pg:"description" yaml:"description"`
	Priority    Priority    `protobuf:"varint,3,opt,name=priority,proto3,enum=tooling.lineman.v1.Priority" json:"priority" bun:"priority" csv:"priority" pg:"priority" yaml:"priority"`
	Recurrence  *Recurrence `protobuf:"bytes,4,opt,name=recurrence,proto3" json:"recurrence" bun:"recurrence" csv:"recurrence" pg:"recurrence" yaml:"recurrence"`
}

func (x *CreateLoopRequest) Reset() {
	*x = CreateLoopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoopRequest) ProtoMessage() {}

func (x *CreateLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoopRequest.ProtoReflect.Descriptor instead.
func (*CreateLoopRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{22}
}

func (x *CreateLoopRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

func (x *CreateLoopRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLoopRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateLoopRequest) GetRecurrence() *Recurrence {
	if x != nil {
		return x.Recurrence
	}
	return nil
}

type ListLoopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectiveId string `protobuf:"bytes,1,opt,name=objective_id,json=objectiveId,proto3" json:"objective_id" bun:"objective_id" csv:"objective_id" pg:"objective_id" yaml:"objective_id"` // optional filter
}

func (x *ListLoopsRequest) Reset() {
	*x = ListLoopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLoopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoopsRequest) ProtoMessage() {}

func (x *ListLoopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoopsRequest.ProtoReflect.Descriptor instead.
func (*ListLoopsRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{23}
}

func (x *ListLoopsRequest) GetObjectiveId() string {
	if x != nil {
		return x.ObjectiveId
	}
	return ""
}

type ListLoopsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loops []*Loop `protobuf:"bytes,1,rep,name=loops,proto3" json:"loops" bun:"loops" csv:"loops" pg:"loops" yaml:"loops"`
}

func (x *ListLoopsResponse) Reset() {
	*x = ListLoopsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLoopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoopsResponse) ProtoMessage() {}

func (x *ListLoopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoopsResponse.ProtoReflect.Descriptor instead.
func (*ListLoopsResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListLoopsResponse) GetLoops() []*Loop {
	if x != nil {
		return x.Loops
	}
	return nil
}

type PauseLoopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bun:"id" csv:"id" pg:"id" yaml:"id"`
}

func (x *PauseLoopRequest) Reset() {
	*x = PauseLoopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseLoopRequest) ProtoMessage() {}

func (x *PauseLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseLoopRequest.ProtoReflect.Descriptor instead.
func (*PauseLoopRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{25}
}

func (x *PauseLoopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResumeLoopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bun:"id" csv:"id" pg:"id" yaml:"id"`
}

func (x *ResumeLoopRequest) Reset() {
	*x = ResumeLoopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeLoopRequest) ProtoMessage() {}

func (x *ResumeLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeLoopRequest.ProtoReflect.Descriptor instead.
func (*ResumeLoopRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{26}
}

func (x *ResumeLoopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLoopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bun:"id" csv:"id" pg:"id" yaml:"id"`
}

func (x *DeleteLoopRequest) Reset() {
	*x = DeleteLoopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoopRequest) ProtoMessage() {}

func (x *DeleteLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoopRequest.ProtoReflect.Descriptor instead.
func (*DeleteLoopRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteLoopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLoopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteLoopResponse) Reset() {
	*x = DeleteLoopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoopResponse) ProtoMessage() {}

func (x *DeleteLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoopResponse.ProtoReflect.Descriptor instead.
func (*DeleteLoopResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{28}
}

type WatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{29}
}

type WatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Item:
	//
	//	*WatchResponse_Task
	//	*WatchResponse_Agent
	//	*WatchResponse_ScheduledTask
	//	*WatchResponse_Loop
	Item    isWatchResponse_Item `protobuf_oneof:"item"`
	Removed bool                 `protobuf:"varint,5,opt,name=removed,proto3" json:"removed" bun:"removed" csv:"removed" pg:"removed" yaml:"removed"`
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tooling_lineman_v1_service_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_lineman_v1_service_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_tooling_lineman_v1_service_proto_rawDescGZIP(), []int{30}
}

func (m *WatchResponse) GetItem() isWatchResponse_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (x *WatchResponse) GetTask() *Task {
	if x, ok := x.GetItem().(*WatchResponse_Task); ok {
		return x.Task
	}
	return nil
}

func (x *WatchResponse) GetAgent() *Agent {
	if x, ok := x.GetItem().(*WatchResponse_Agent); ok {
		return x.Agent
	}
	return nil
}

func (x *WatchResponse) GetScheduledTask() *ScheduledTask {
	if x, ok := x.GetItem().(*WatchResponse_ScheduledTask); ok {
		return x.ScheduledTask
	}
	return nil
}

func (x *WatchResponse) GetLoop() *Loop {
	if x, ok := x.GetItem().(*WatchResponse_Loop); ok {
		return x.Loop
	}
	return nil
}

func (x *WatchResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type isWatchResponse_Item interface {
	isWatchResponse_Item()
}

type WatchResponse_Task struct {
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3,oneof" bun:"task" csv:"task" json:"task" pg:"task" yaml:"task"`
}

type WatchResponse_Agent struct {
	Agent *Agent `protobuf:"bytes,2,opt,name=agent,proto3,oneof" bun:"agent" csv:"agent" json:"agent" pg:"agent" yaml:"agent"`
}

type WatchResponse_ScheduledTask struct {
	ScheduledTask *ScheduledTask `protobuf:"bytes,3,opt,name=scheduled_task,json=scheduledTask,proto3,oneof" bun:"scheduled_task" csv:"scheduled_task" json:"scheduled_task" pg:"scheduled_task" yaml:"scheduled_task"`
}

type WatchResponse_Loop struct {
	Loop *Loop `protobuf:"bytes,4,opt,name=loop,proto3,oneof" bun:"loop" csv:"loop" json:"loop" pg:"loop" yaml:"loop"`
}

func (*WatchResponse_Task) isWatchResponse_Item() {}

func (*WatchResponse_Agent) isWatchResponse_Item() {}

func (*WatchResponse_ScheduledTask) isWatchResponse_Item() {}

func (*WatchResponse_Loop) isWatchResponse_Item() {}

var File_tooling_lineman_v1_service_proto protoreflect.FileDescriptor

var file_tooling_lineman_v1_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67,
	0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73,
	0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x57, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x0a, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x22, 0xb4, 0x01, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x66, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x11, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22,
	0x4e, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x77, 0x0a, 0x12, 0x52, 0x65, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x0e, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x66, 0x74,
	0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0xd9, 0x01, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x3c, 0x0a, 0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x13,
	0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x64, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x6c, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x47, 0x75, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0xd0, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x74, 0x6f,
	0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x66, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x06, 0x66, 0x69, 0x72, 0x65, 0x41, 0x74, 0x22, 0x3e, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x73, 0x22, 0x2c, 0x0a, 0x1a, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0xd2, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x74,
	0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x22, 0x35, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x6f, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x4c, 0x6f, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x05, 0x6c, 0x6f, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x05, 0x6c, 0x6f, 0x6f, 0x70, 0x73,
	0x22, 0x22, 0x0a, 0x10, 0x50, 0x61, 0x75, 0x73, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x4c, 0x6f,
	0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x90, 0x02, 0x0a, 0x0d, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00,
	0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x31, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x4a, 0x0a, 0x0e, 0x73, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x70, 0x48, 0x00, 0x52,
	0x04, 0x6c, 0x6f, 0x6f, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x42,
	0x06, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x32, 0xf4, 0x0f, 0x0a, 0x0e, 0x4c, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x2a, 0x2e,
	0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x27, 0x2e, 0x74, 0x6f, 0x6f,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x29, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67,
	0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2a, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x25, 0x2e,
	0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00,
	0x12, 0x49, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x22, 0x2e, 0x74, 0x6f,
	0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x09, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x24, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x74, 0x6f, 0x6f,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67,
	0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x22, 0x00, 0x12, 0x51, 0x0a, 0x0b, 0x52, 0x65, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x26, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74,
	0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x24, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x74, 0x6f,
	0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x25, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e,
	0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x74, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x27, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74,
	0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x47, 0x75, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2a, 0x2e, 0x74, 0x6f,
	0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x47, 0x75, 0x69, 0x64, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2e, 0x2e, 0x74, 0x6f, 0x6f,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x6f, 0x6f,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12,
	0x75, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x2d, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x78, 0x0a, 0x13, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2e, 0x2e,
	0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e,
	0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x25,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x70, 0x22,
	0x00, 0x12, 0x5a, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x6f, 0x70, 0x73, 0x12, 0x24,
	0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f,
	0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a,
	0x09, 0x50, 0x61, 0x75, 0x73, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x24, 0x2e, 0x74, 0x6f, 0x6f,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x75, 0x73, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x70, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x25, 0x2e, 0x74, 0x6f, 0x6f,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x70, 0x22, 0x00, 0x12, 0x5d, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x25, 0x2e, 0x74, 0x6f,
	0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x69, 0x6e,
	0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x05,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x20, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x36,
	0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65,
	0x61, 0x64, 0x79, 0x2d, 0x62, 0x79, 0x74, 0x65, 0x73, 0x2f, 0x64, 0x72, 0x61, 0x66, 0x74, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x6c, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tooling_lineman_v1_service_proto_rawDescOnce sync.Once
	file_tooling_lineman_v1_service_proto_rawDescData = file_tooling_lineman_v1_service_proto_rawDesc
)

func file_tooling_lineman_v1_service_proto_rawDescGZIP() []byte {
	file_tooling_lineman_v1_service_proto_rawDescOnce.Do(func() {
		file_tooling_lineman_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_tooling_lineman_v1_service_proto_rawDescData)
	})
	return file_tooling_lineman_v1_service_proto_rawDescData
}

var file_tooling_lineman_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_tooling_lineman_v1_service_proto_goTypes = []any{
	(*CreateObjectiveRequest)(nil),      // 0: tooling.lineman.v1.CreateObjectiveRequest
	(*GetObjectiveRequest)(nil),         // 1: tooling.lineman.v1.GetObjectiveRequest
	(*ListObjectivesRequest)(nil),       // 2: tooling.lineman.v1.ListObjectivesRequest
	(*ListObjectivesResponse)(nil),      // 3: tooling.lineman.v1.ListObjectivesResponse
	(*CreateTaskRequest)(nil),           // 4: tooling.lineman.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),              // 5: tooling.lineman.v1.GetTaskRequest
	(*ListTasksRequest)(nil),            // 6: tooling.lineman.v1.ListTasksRequest
	(*ListTasksResponse)(nil),           // 7: tooling.lineman.v1.ListTasksResponse
	(*UpdateTaskStateRequest)(nil),      // 8: tooling.lineman.v1.UpdateTaskStateRequest
	(*ReorderTaskRequest)(nil),          // 9: tooling.lineman.v1.ReorderTaskRequest
	(*AssignAgentRequest)(nil),          // 10: tooling.lineman.v1.AssignAgentRequest
	(*HeartbeatRequest)(nil),            // 11: tooling.lineman.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 12: tooling.lineman.v1.HeartbeatResponse
	(*ListAgentsRequest)(nil),           // 13: tooling.lineman.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),          // 14: tooling.lineman.v1.ListAgentsResponse
	(*RequestInputRequest)(nil),         // 15: tooling.lineman.v1.RequestInputRequest
	(*ProvideGuidanceRequest)(nil),      // 16: tooling.lineman.v1.ProvideGuidanceRequest
	(*CreateScheduledTaskRequest)(nil),  // 17: tooling.lineman.v1.CreateScheduledTaskRequest
	(*ListScheduledTasksRequest)(nil),   // 18: tooling.lineman.v1.ListScheduledTasksRequest
	(*ListScheduledTasksResponse)(nil),  // 19: tooling.lineman.v1.ListScheduledTasksResponse
	(*CancelScheduledTaskRequest)(nil),  // 20: tooling.lineman.v1.CancelScheduledTaskRequest
	(*CancelScheduledTaskResponse)(nil), // 21: tooling.lineman.v1.CancelScheduledTaskResponse
	(*CreateLoopRequest)(nil),           // 22: tooling.lineman.v1.CreateLoopRequest
	(*ListLoopsRequest)(nil),            // 23: tooling.lineman.v1.ListLoopsRequest
	(*ListLoopsResponse)(nil),           // 24: tooling.lineman.v1.ListLoopsResponse
	(*PauseLoopRequest)(nil),            // 25: tooling.lineman.v1.PauseLoopRequest
	(*ResumeLoopRequest)(nil),           // 26: tooling.lineman.v1.ResumeLoopRequest
	(*DeleteLoopRequest)(nil),           // 27: tooling.lineman.v1.DeleteLoopRequest
	(*DeleteLoopResponse)(nil),          // 28: tooling.lineman.v1.DeleteLoopResponse
	(*WatchRequest)(nil),                // 29: tooling.lineman.v1.WatchRequest
	(*WatchResponse)(nil),               // 30: tooling.lineman.v1.WatchResponse
	(*Objective)(nil),                   // 31: tooling.lineman.v1.Objective
	(Priority)(0),                       // 32: tooling.lineman.v1.Priority
	(*Task)(nil),                        // 33: tooling.lineman.v1.Task
	(AgentKind)(0),                      // 34: tooling.lineman.v1.AgentKind
	(*Agent)(nil),                       // 35: tooling.lineman.v1.Agent
	(*timestamppb.Timestamp)(nil),       // 36: google.protobuf.Timestamp
	(*ScheduledTask)(nil),               // 37: tooling.lineman.v1.ScheduledTask
	(*Recurrence)(nil),                  // 38: tooling.lineman.v1.Recurrence
	(*Loop)(nil),                        // 39: tooling.lineman.v1.Loop
}
var file_tooling_lineman_v1_service_proto_depIdxs = []int32{
	31, // 0: tooling.lineman.v1.ListObjectivesResponse.objectives:type_name -> tooling.lineman.v1.Objective
	32, // 1: tooling.lineman.v1.CreateTaskRequest.priority:type_name -> tooling.lineman.v1.Priority
	33, // 2: tooling.lineman.v1.ListTasksResponse.tasks:type_name -> tooling.lineman.v1.Task
	34, // 3: tooling.lineman.v1.HeartbeatRequest.agent_kind:type_name -> tooling.lineman.v1.AgentKind
	35, // 4: tooling.lineman.v1.ListAgentsResponse.agents:type_name -> tooling.lineman.v1.Agent
	32, // 5: tooling.lineman.v1.CreateScheduledTaskRequest.priority:type_name -> tooling.lineman.v1.Priority
	36, // 6: tooling.lineman.v1.CreateScheduledTaskRequest.fire_at:type_name -> google.protobuf.Timestamp
	37, // 7: tooling.lineman.v1.ListScheduledTasksResponse.scheduled_tasks:type_name -> tooling.lineman.v1.ScheduledTask
	32, // 8: tooling.lineman.v1.CreateLoopRequest.priority:type_name -> tooling.lineman.v1.Priority
	38, // 9: tooling.lineman.v1.CreateLoopRequest.recurrence:type_name -> tooling.lineman.v1.Recurrence
	39, // 10: tooling.lineman.v1.ListLoopsResponse.loops:type_name -> tooling.lineman.v1.Loop
	33, // 11: tooling.lineman.v1.WatchResponse.task:type_name -> tooling.lineman.v1.Task
	35, // 12: tooling.lineman.v1.WatchResponse.agent:type_name -> tooling.lineman.v1.Agent
	37, // 13: tooling.lineman.v1.WatchResponse.scheduled_task:type_name -> tooling.lineman.v1.ScheduledTask
	39, // 14: tooling.lineman.v1.WatchResponse.loop:type_name -> tooling.lineman.v1.Loop
	0,  // 15: tooling.lineman.v1.LinemanService.CreateObjective:input_type -> tooling.lineman.v1.CreateObjectiveRequest
	1,  // 16: tooling.lineman.v1.LinemanService.GetObjective:input_type -> tooling.lineman.v1.GetObjectiveRequest
	2,  // 17: tooling.lineman.v1.LinemanService.ListObjectives:input_type -> tooling.lineman.v1.ListObjectivesRequest
	4,  // 18: tooling.lineman.v1.LinemanService.CreateTask:input_type -> tooling.lineman.v1.CreateTaskRequest
	5,  // 19: tooling.lineman.v1.LinemanService.GetTask:input_type -> tooling.lineman.v1.GetTaskRequest
	6,  // 20: tooling.lineman.v1.LinemanService.ListTasks:input_type -> tooling.lineman.v1.ListTasksRequest
	8,  // 21: tooling.lineman.v1.LinemanService.UpdateTaskState:input_type -> tooling.lineman.v1.UpdateTaskStateRequest
	9,  // 22: tooling.lineman.v1.LinemanService.ReorderTask:input_type -> tooling.lineman.v1.ReorderTaskRequest
	10, // 23: tooling.lineman.v1.LinemanService.AssignAgent:input_type -> tooling.lineman.v1.AssignAgentRequest
	11, // 24: tooling.lineman.v1.LinemanService.Heartbeat:input_type -> tooling.lineman.v1.HeartbeatRequest
	13, // 25: tooling.lineman.v1.LinemanService.ListAgents:input_type -> tooling.lineman.v1.ListAgentsRequest
	15, // 26: tooling.lineman.v1.LinemanService.RequestInput:input_type -> tooling.lineman.v1.RequestInputRequest
	16, // 27: tooling.lineman.v1.LinemanService.ProvideGuidance:input_type -> tooling.lineman.v1.ProvideGuidanceRequest
	17, // 28: tooling.lineman.v1.LinemanService.CreateScheduledTask:input_type -> tooling.lineman.v1.CreateScheduledTaskRequest
	18, // 29: tooling.lineman.v1.LinemanService.ListScheduledTasks:input_type -> tooling.lineman.v1.ListScheduledTasksRequest
	20, // 30: tooling.lineman.v1.LinemanService.CancelScheduledTask:input_type -> tooling.lineman.v1.CancelScheduledTaskRequest
	22, // 31: tooling.lineman.v1.LinemanService.CreateLoop:input_type -> tooling.lineman.v1.CreateLoopRequest
	23, // 32: tooling.lineman.v1.LinemanService.ListLoops:input_type -> tooling.lineman.v1.ListLoopsRequest
	25, // 33: tooling.lineman.v1.LinemanService.PauseLoop:input_type -> tooling.lineman.v1.PauseLoopRequest
	26, // 34: tooling.lineman.v1.LinemanService.ResumeLoop:input_type -> tooling.lineman.v1.ResumeLoopRequest
	27, // 35: tooling.lineman.v1.LinemanService.DeleteLoop:input_type -> tooling.lineman.v1.DeleteLoopRequest
	29, // 36: tooling.lineman.v1.LinemanService.Watch:input_type -> tooling.lineman.v1.WatchRequest
	31, // 37: tooling.lineman.v1.LinemanService.CreateObjective:output_type -> tooling.lineman.v1.Objective
	31, // 38: tooling.lineman.v1.LinemanService.GetObjective:output_type -> tooling.lineman.v1.Objective
	3,  // 39: tooling.lineman.v1.LinemanService.ListObjectives:output_type -> tooling.lineman.v1.ListObjectivesResponse
	33, // 40: tooling.lineman.v1.LinemanService.CreateTask:output_type -> tooling.lineman.v1.Task
	33, // 41: tooling.lineman.v1.LinemanService.GetTask:output_type -> tooling.lineman.v1.Task
	7,  // 42: tooling.lineman.v1.LinemanService.ListTasks:output_type -> tooling.lineman.v1.ListTasksResponse
	33, // 43: tooling.lineman.v1.LinemanService.UpdateTaskState:output_type -> tooling.lineman.v1.Task
	33, // 44: tooling.lineman.v1.LinemanService.ReorderTask:output_type -> tooling.lineman.v1.Task
	33, // 45: tooling.lineman.v1.LinemanService.AssignAgent:output_type -> tooling.lineman.v1.Task
	12, // 46: tooling.lineman.v1.LinemanService.Heartbeat:output_type -> tooling.lineman.v1.HeartbeatResponse
	14, // 47: tooling.lineman.v1.LinemanService.ListAgents:output_type -> tooling.lineman.v1.ListAgentsResponse
	33, // 48: tooling.lineman.v1.LinemanService.RequestInput:output_type -> tooling.lineman.v1.Task
	33, // 49: tooling.lineman.v1.LinemanService.ProvideGuidance:output_type -> tooling.lineman.v1.Task
	37, // 50: tooling.lineman.v1.LinemanService.CreateScheduledTask:output_type -> tooling.lineman.v1.ScheduledTask
	19, // 51: tooling.lineman.v1.LinemanService.ListScheduledTasks:output_type -> tooling.lineman.v1.ListScheduledTasksResponse
	21, // 52: tooling.lineman.v1.LinemanService.CancelScheduledTask:output_type -> tooling.lineman.v1.CancelScheduledTaskResponse
	39, // 53: tooling.lineman.v1.LinemanService.CreateLoop:output_type -> tooling.lineman.v1.Loop
	24, // 54: tooling.lineman.v1.LinemanService.ListLoops:output_type -> tooling.lineman.v1.ListLoopsResponse
	39, // 55: tooling.lineman.v1.LinemanService.PauseLoop:output_type -> tooling.lineman.v1.Loop
	39, // 56: tooling.lineman.v1.LinemanService.ResumeLoop:output_type -> tooling.lineman.v1.Loop
	28, // 57: tooling.lineman.v1.LinemanService.DeleteLoop:output_type -> tooling.lineman.v1.DeleteLoopResponse
	30, // 58: tooling.lineman.v1.LinemanService.Watch:output_type -> tooling.lineman.v1.WatchResponse
	37, // [37:59] is the sub-list for method output_type
	15, // [15:37] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_tooling_lineman_v1_service_proto_init() }
func file_tooling_lineman_v1_service_proto_init() {
	if File_tooling_lineman_v1_service_proto != nil {
		return
	}
	file_tooling_lineman_v1_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tooling_lineman_v1_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateObjectiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetObjectiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListObjectivesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListObjectivesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTaskStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ReorderTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*AssignAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ListAgentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ListAgentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RequestInputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ProvideGuidanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*CreateScheduledTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ListScheduledTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*ListScheduledTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*CancelScheduledTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*CancelScheduledTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLoopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*ListLoopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*ListLoopsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*PauseLoopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeLoopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLoopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteLoopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*WatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tooling_lineman_v1_service_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*WatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tooling_lineman_v1_service_proto_msgTypes[30].OneofWrappers = []any{
		(*WatchResponse_Task)(nil),
		(*WatchResponse_Agent)(nil),
		(*WatchResponse_ScheduledTask)(nil),
		(*WatchResponse_Loop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tooling_lineman_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tooling_lineman_v1_service_proto_goTypes,
		DependencyIndexes: file_tooling_lineman_v1_service_proto_depIdxs,
		MessageInfos:      file_tooling_lineman_v1_service_proto_msgTypes,
	}.Build()
	File_tooling_lineman_v1_service_proto = out.File
	file_tooling_lineman_v1_service_proto_rawDesc = nil
	file_tooling_lineman_v1_service_proto_goTypes = nil
	file_tooling_lineman_v1_service_proto_depIdxs = nil
}
