// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/registry/key_value/v1/models.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Value - The message that is used to save a value in the `key_value` store.
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_core_registry_key_value_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_core_registry_key_value_v1_models_proto protoreflect.FileDescriptor

const file_core_registry_key_value_v1_models_proto_rawDesc = "" +
	"\n" +
	"'core/registry/key_value/v1/models.proto\x12\x1acore.registry.key_value.v1\"\x1b\n" +
	"\x05Value\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04dataB>Z<github.com/steady-bytes/draft/api/core/registry/key_value/v1b\x06proto3"

var (
	file_core_registry_key_value_v1_models_proto_rawDescOnce sync.Once
	file_core_registry_key_value_v1_models_proto_rawDescData []byte
)

func file_core_registry_key_value_v1_models_proto_rawDescGZIP() []byte {
	file_core_registry_key_value_v1_models_proto_rawDescOnce.Do(func() {
		file_core_registry_key_value_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_registry_key_value_v1_models_proto_rawDesc), len(file_core_registry_key_value_v1_models_proto_rawDesc)))
	})
	return file_core_registry_key_value_v1_models_proto_rawDescData
}

var file_core_registry_key_value_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_registry_key_value_v1_models_proto_goTypes = []any{
	(*Value)(nil), // 0: core.registry.key_value.v1.Value
}
var file_core_registry_key_value_v1_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_registry_key_value_v1_models_proto_init() }
func file_core_registry_key_value_v1_models_proto_init() {
	if File_core_registry_key_value_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_registry_key_value_v1_models_proto_rawDesc), len(file_core_registry_key_value_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_registry_key_value_v1_models_proto_goTypes,
		DependencyIndexes: file_core_registry_key_value_v1_models_proto_depIdxs,
		MessageInfos:      file_core_registry_key_value_v1_models_proto_msgTypes,
	}.Build()
	File_core_registry_key_value_v1_models_proto = out.File
	file_core_registry_key_value_v1_models_proto_goTypes = nil
	file_core_registry_key_value_v1_models_proto_depIdxs = nil
}
