// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/registry/key_value/v1/nav_config.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NavigationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationItem) Reset() {
	*x = NavigationItem{}
	mi := &file_core_registry_key_value_v1_nav_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationItem) ProtoMessage() {}

func (x *NavigationItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_nav_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationItem.ProtoReflect.Descriptor instead.
func (*NavigationItem) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_nav_config_proto_rawDescGZIP(), []int{0}
}

func (x *NavigationItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NavigationItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NavigationSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Items         []*NavigationItem      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationSection) Reset() {
	*x = NavigationSection{}
	mi := &file_core_registry_key_value_v1_nav_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationSection) ProtoMessage() {}

func (x *NavigationSection) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_nav_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationSection.ProtoReflect.Descriptor instead.
func (*NavigationSection) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_nav_config_proto_rawDescGZIP(), []int{1}
}

func (x *NavigationSection) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NavigationSection) GetItems() []*NavigationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type NavigationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*NavigationSection   `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationConfig) Reset() {
	*x = NavigationConfig{}
	mi := &file_core_registry_key_value_v1_nav_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationConfig) ProtoMessage() {}

func (x *NavigationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_nav_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationConfig.ProtoReflect.Descriptor instead.
func (*NavigationConfig) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_nav_config_proto_rawDescGZIP(), []int{2}
}

func (x *NavigationConfig) GetSections() []*NavigationSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

var File_core_registry_key_value_v1_nav_config_proto protoreflect.FileDescriptor

const file_core_registry_key_value_v1_nav_config_proto_rawDesc = "" +
	"\n" +
	"+core/registry/key_value/v1/nav_config.proto\x12\x1acore.registry.key_value.v1\":\n" +
	"\x0eNavigationItem\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"k\n" +
	"\x11NavigationSection\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12@\n" +
	"\x05items\x18\x02 \x03(\v2*.core.registry.key_value.v1.NavigationItemR\x05items\"]\n" +
	"\x10NavigationConfig\x12I\n" +
	"\bsections\x18\x01 \x03(\v2-.core.registry.key_value.v1.NavigationSectionR\bsectionsB>Z<github.com/steady-bytes/draft/api/core/registry/key_value/v1b\x06proto3"

var (
	file_core_registry_key_value_v1_nav_config_proto_rawDescOnce sync.Once
	file_core_registry_key_value_v1_nav_config_proto_rawDescData []byte
)

func file_core_registry_key_value_v1_nav_config_proto_rawDescGZIP() []byte {
	file_core_registry_key_value_v1_nav_config_proto_rawDescOnce.Do(func() {
		file_core_registry_key_value_v1_nav_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_registry_key_value_v1_nav_config_proto_rawDesc), len(file_core_registry_key_value_v1_nav_config_proto_rawDesc)))
	})
	return file_core_registry_key_value_v1_nav_config_proto_rawDescData
}

var file_core_registry_key_value_v1_nav_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_registry_key_value_v1_nav_config_proto_goTypes = []any{
	(*NavigationItem)(nil),    // 0: core.registry.key_value.v1.NavigationItem
	(*NavigationSection)(nil), // 1: core.registry.key_value.v1.NavigationSection
	(*NavigationConfig)(nil),  // 2: core.registry.key_value.v1.NavigationConfig
}
var file_core_registry_key_value_v1_nav_config_proto_depIdxs = []int32{
	0, // 0: core.registry.key_value.v1.NavigationSection.items:type_name -> core.registry.key_value.v1.NavigationItem
	1, // 1: core.registry.key_value.v1.NavigationConfig.sections:type_name -> core.registry.key_value.v1.NavigationSection
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_registry_key_value_v1_nav_config_proto_init() }
func file_core_registry_key_value_v1_nav_config_proto_init() {
	if File_core_registry_key_value_v1_nav_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_registry_key_value_v1_nav_config_proto_rawDesc), len(file_core_registry_key_value_v1_nav_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_registry_key_value_v1_nav_config_proto_goTypes,
		DependencyIndexes: file_core_registry_key_value_v1_nav_config_proto_depIdxs,
		MessageInfos:      file_core_registry_key_value_v1_nav_config_proto_msgTypes,
	}.Build()
	File_core_registry_key_value_v1_nav_config_proto = out.File
	file_core_registry_key_value_v1_nav_config_proto_goTypes = nil
	file_core_registry_key_value_v1_nav_config_proto_depIdxs = nil
}
