// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/registry/key_value/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *anypb.Any             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value is only used to determine the underlying type, the content within the type does not matter
	Value         *anypb.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *anypb.Any             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*anypb.Any  `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_key_value_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_key_value_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_core_registry_key_value_v1_service_proto protoreflect.FileDescriptor

const file_core_registry_key_value_v1_service_proto_rawDesc = "" +
	"\n" +
	"(core/registry/key_value/v1/service.proto\x12\x1acore.registry.key_value.v1\x1a\x19google/protobuf/any.proto\"J\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\x1f\n" +
	"\vSetResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"J\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\"9\n" +
	"\vGetResponse\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\"M\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\"\n" +
	"\x0eDeleteResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vListRequest\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\xad\x01\n" +
	"\fListResponse\x12L\n" +
	"\x06values\x18\x02 \x03(\v24.core.registry.key_value.v1.ListResponse.ValuesEntryR\x06values\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x012\x85\x03\n" +
	"\x0fKeyValueService\x12X\n" +
	"\x03Set\x12&.core.registry.key_value.v1.SetRequest\x1a'.core.registry.key_value.v1.SetResponse\"\x00\x12X\n" +
	"\x03Get\x12&.core.registry.key_value.v1.GetRequest\x1a'.core.registry.key_value.v1.GetResponse\"\x00\x12a\n" +
	"\x06Delete\x12).core.registry.key_value.v1.DeleteRequest\x1a*.core.registry.key_value.v1.DeleteResponse\"\x00\x12[\n" +
	"\x04List\x12'.core.registry.key_value.v1.ListRequest\x1a(.core.registry.key_value.v1.ListResponse\"\x00B>Z<github.com/steady-bytes/draft/api/core/registry/key_value/v1b\x06proto3"

var (
	file_core_registry_key_value_v1_service_proto_rawDescOnce sync.Once
	file_core_registry_key_value_v1_service_proto_rawDescData []byte
)

func file_core_registry_key_value_v1_service_proto_rawDescGZIP() []byte {
	file_core_registry_key_value_v1_service_proto_rawDescOnce.Do(func() {
		file_core_registry_key_value_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_registry_key_value_v1_service_proto_rawDesc), len(file_core_registry_key_value_v1_service_proto_rawDesc)))
	})
	return file_core_registry_key_value_v1_service_proto_rawDescData
}

var file_core_registry_key_value_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_core_registry_key_value_v1_service_proto_goTypes = []any{
	(*SetRequest)(nil),     // 0: core.registry.key_value.v1.SetRequest
	(*SetResponse)(nil),    // 1: core.registry.key_value.v1.SetResponse
	(*GetRequest)(nil),     // 2: core.registry.key_value.v1.GetRequest
	(*GetResponse)(nil),    // 3: core.registry.key_value.v1.GetResponse
	(*DeleteRequest)(nil),  // 4: core.registry.key_value.v1.DeleteRequest
	(*DeleteResponse)(nil), // 5: core.registry.key_value.v1.DeleteResponse
	(*ListRequest)(nil),    // 6: core.registry.key_value.v1.ListRequest
	(*ListResponse)(nil),   // 7: core.registry.key_value.v1.ListResponse
	nil,                    // 8: core.registry.key_value.v1.ListResponse.ValuesEntry
	(*anypb.Any)(nil),      // 9: google.protobuf.Any
}
var file_core_registry_key_value_v1_service_proto_depIdxs = []int32{
	9,  // 0: core.registry.key_value.v1.SetRequest.value:type_name -> google.protobuf.Any
	9,  // 1: core.registry.key_value.v1.GetRequest.value:type_name -> google.protobuf.Any
	9,  // 2: core.registry.key_value.v1.GetResponse.value:type_name -> google.protobuf.Any
	9,  // 3: core.registry.key_value.v1.DeleteRequest.value:type_name -> google.protobuf.Any
	9,  // 4: core.registry.key_value.v1.ListRequest.value:type_name -> google.protobuf.Any
	8,  // 5: core.registry.key_value.v1.ListResponse.values:type_name -> core.registry.key_value.v1.ListResponse.ValuesEntry
	9,  // 6: core.registry.key_value.v1.ListResponse.ValuesEntry.value:type_name -> google.protobuf.Any
	0,  // 7: core.registry.key_value.v1.KeyValueService.Set:input_type -> core.registry.key_value.v1.SetRequest
	2,  // 8: core.registry.key_value.v1.KeyValueService.Get:input_type -> core.registry.key_value.v1.GetRequest
	4,  // 9: core.registry.key_value.v1.KeyValueService.Delete:input_type -> core.registry.key_value.v1.DeleteRequest
	6,  // 10: core.registry.key_value.v1.KeyValueService.List:input_type -> core.registry.key_value.v1.ListRequest
	1,  // 11: core.registry.key_value.v1.KeyValueService.Set:output_type -> core.registry.key_value.v1.SetResponse
	3,  // 12: core.registry.key_value.v1.KeyValueService.Get:output_type -> core.registry.key_value.v1.GetResponse
	5,  // 13: core.registry.key_value.v1.KeyValueService.Delete:output_type -> core.registry.key_value.v1.DeleteResponse
	7,  // 14: core.registry.key_value.v1.KeyValueService.List:output_type -> core.registry.key_value.v1.ListResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_core_registry_key_value_v1_service_proto_init() }
func file_core_registry_key_value_v1_service_proto_init() {
	if File_core_registry_key_value_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_registry_key_value_v1_service_proto_rawDesc), len(file_core_registry_key_value_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_registry_key_value_v1_service_proto_goTypes,
		DependencyIndexes: file_core_registry_key_value_v1_service_proto_depIdxs,
		MessageInfos:      file_core_registry_key_value_v1_service_proto_msgTypes,
	}.Build()
	File_core_registry_key_value_v1_service_proto = out.File
	file_core_registry_key_value_v1_service_proto_goTypes = nil
	file_core_registry_key_value_v1_service_proto_depIdxs = nil
}
