// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tooling/step_executor/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StepRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StepName string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name" bun:"step_name" csv:"step_name" pg:"step_name" yaml:"step_name"`
	// config is the step's `with:` block, passed through opaquely — its
	// shape is defined by whatever config_schema the plugin published to
	// Foundry, not by this proto.
	Config *structpb.Struct `protobuf:"bytes,2,opt,name=config,proto3" json:"config" bun:"config" csv:"config" pg:"config" yaml:"config"`
	// context carries resolved {{ steps.X.result }} references from earlier
	// steps in the same run, keyed by step name.
	Context       *structpb.Struct `protobuf:"bytes,3,opt,name=context,proto3" json:"context" bun:"context" csv:"context" pg:"context" yaml:"context"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_tooling_step_executor_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_step_executor_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_tooling_step_executor_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *StepRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StepRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type StepResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" bun:"success" csv:"success" pg:"success" yaml:"success"`
	// result is available to later steps via {{ steps.<name>.result }}.
	Result        *structpb.Struct `protobuf:"bytes,2,opt,name=result,proto3" json:"result" bun:"result" csv:"result" pg:"result" yaml:"result"`
	Error         string           `protobuf:"bytes,3,opt,name=error,proto3" json:"error" bun:"error" csv:"error" pg:"error" yaml:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_tooling_step_executor_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_step_executor_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_tooling_step_executor_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *StepResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StepResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StepResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tooling_step_executor_v1_service_proto protoreflect.FileDescriptor

const file_tooling_step_executor_v1_service_proto_rawDesc = "" +
	"\n" +
	"&tooling/step_executor/v1/service.proto\x12\x18tooling.step_executor.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x8e\x01\n" +
	"\vStepRequest\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\"o\n" +
	"\fStepResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2j\n" +
	"\fStepExecutor\x12Z\n" +
	"\aExecute\x12%.tooling.step_executor.v1.StepRequest\x1a&.tooling.step_executor.v1.StepResponse\"\x00B<Z:github.com/steady-bytes/draft/api/tooling/step_executor/v1b\x06proto3"

var (
	file_tooling_step_executor_v1_service_proto_rawDescOnce sync.Once
	file_tooling_step_executor_v1_service_proto_rawDescData []byte
)

func file_tooling_step_executor_v1_service_proto_rawDescGZIP() []byte {
	file_tooling_step_executor_v1_service_proto_rawDescOnce.Do(func() {
		file_tooling_step_executor_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tooling_step_executor_v1_service_proto_rawDesc), len(file_tooling_step_executor_v1_service_proto_rawDesc)))
	})
	return file_tooling_step_executor_v1_service_proto_rawDescData
}

var file_tooling_step_executor_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tooling_step_executor_v1_service_proto_goTypes = []any{
	(*StepRequest)(nil),     // 0: tooling.step_executor.v1.StepRequest
	(*StepResponse)(nil),    // 1: tooling.step_executor.v1.StepResponse
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_tooling_step_executor_v1_service_proto_depIdxs = []int32{
	2, // 0: tooling.step_executor.v1.StepRequest.config:type_name -> google.protobuf.Struct
	2, // 1: tooling.step_executor.v1.StepRequest.context:type_name -> google.protobuf.Struct
	2, // 2: tooling.step_executor.v1.StepResponse.result:type_name -> google.protobuf.Struct
	0, // 3: tooling.step_executor.v1.StepExecutor.Execute:input_type -> tooling.step_executor.v1.StepRequest
	1, // 4: tooling.step_executor.v1.StepExecutor.Execute:output_type -> tooling.step_executor.v1.StepResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tooling_step_executor_v1_service_proto_init() }
func file_tooling_step_executor_v1_service_proto_init() {
	if File_tooling_step_executor_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tooling_step_executor_v1_service_proto_rawDesc), len(file_tooling_step_executor_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tooling_step_executor_v1_service_proto_goTypes,
		DependencyIndexes: file_tooling_step_executor_v1_service_proto_depIdxs,
		MessageInfos:      file_tooling_step_executor_v1_service_proto_msgTypes,
	}.Build()
	File_tooling_step_executor_v1_service_proto = out.File
	file_tooling_step_executor_v1_service_proto_goTypes = nil
	file_tooling_step_executor_v1_service_proto_depIdxs = nil
}
