// This file is @generated by prost-build.
/// AddRouteRequest - Add a route to the networking configuration
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddRouteRequest {
    /// should this be the route type from envoy config. So that I can use the same proto
    /// or should I make an internal proto and convert them back and forth
    /// An advantage of using the envoy `Route` proto is that it's already ubuqitous in the
    /// wild. A disadvantage is that it's a bit more complex than what I need.
    #[prost(message, optional, tag = "1")]
    pub route: ::core::option::Option<Route>,
}
/// AddRouteResponse - Response to adding a route to the networking configuration. Just because a message
/// was received doesn't mean it was successful. The `code` field is used to determine the success of the
/// route entry.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddRouteResponse {
    #[prost(enumeration = "AddRouteResponseCode", tag = "1")]
    pub code: i32,
    /// Human-readable detail, populated on non-OK codes (eg. explaining which existing route conflicted).
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Names of existing routes that conflict with the requested route, populated when code is INVALID_REQUEST
    /// due to a conflict.
    #[prost(string, repeated, tag = "3")]
    pub conflicting_routes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRoutesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRoutesResponse {
    #[prost(message, repeated, tag = "1")]
    pub routes: ::prost::alloc::vec::Vec<Route>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteRouteRequest {
    /// route names must be unique making name the primary identifier of a route
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteRouteResponse {
    #[prost(enumeration = "DeleteRouteCode", tag = "1")]
    pub code: i32,
}
/// ValidateRouteRequest - check a candidate route against the existing networking configuration
/// without persisting it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateRouteRequest {
    #[prost(message, optional, tag = "1")]
    pub route: ::core::option::Option<Route>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValidateRouteResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    /// Names of existing routes that conflict with the candidate route. Empty when valid is true.
    #[prost(string, repeated, tag = "2")]
    pub conflicting_routes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Human-readable detail, populated when valid is false.
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// RouteAuth declares the authentication policy for a single route. When absent or
/// enabled=false the route is public and no ext_authz check is performed.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RouteAuth {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    #[prost(enumeration = "AuthPolicy", tag = "2")]
    pub policy: i32,
    /// Groups the caller must belong to (AUTH_POLICY_GROUPS).
    #[prost(string, repeated, tag = "3")]
    pub required_groups: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// OAuth2 scopes required on the token (AUTH_POLICY_SCOPES).
    #[prost(string, repeated, tag = "4")]
    pub required_scopes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Route - Close match to the `Route` proto in envoy. Anything that can't be inferred by the draft
/// framework needs to be added by the `process` adding the route configuration.
///
/// The process will register individual routes, while cluster and virtual host configuration will be handled by the framework.
/// current integration is `process` -> `fuse` -> `envoy`
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Route {
    /// Name for the route
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Route matching parameters
    #[prost(message, optional, tag = "2")]
    pub r#match: ::core::option::Option<RouteMatch>,
    /// Endpoint parameters
    #[prost(message, optional, tag = "3")]
    pub endpoint: ::core::option::Option<Endpoint>,
    /// EnableHTTP2 enables HTTP2 support
    #[prost(bool, tag = "4")]
    pub enable_http2: bool,
    /// Auth declares the authentication policy for this route. Optional; defaults to bypass.
    #[prost(message, optional, tag = "5")]
    pub auth: ::core::option::Option<RouteAuth>,
}
/// parameters for the endpoint a route will map to
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Endpoint {
    /// host represents the address of the endpoint (upstream). can be either a hostname or an ip address
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    /// port represents the port on the host of the endpoint (upstream)
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
/// parameters for matching a route
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RouteMatch {
    /// domains for the url a configured in `fuse` but the path to be matched of a route is configured by the `process`
    /// (ie. api.draft.com/health -> /health)
    #[prost(string, tag = "1")]
    pub prefix: ::prost::alloc::string::String,
    /// option to match headers of a request
    /// TODO -> implement pre 1.0 relase of `fuse`
    #[prost(message, optional, tag = "2")]
    pub headers: ::core::option::Option<HeaderMatchOptions>,
    /// options to simplify the matching of a route for grpc. Most request will be grpc and this configuration
    /// makes that integration easier.
    /// TODO -> implement pre 1.0 relase of `fuse`
    #[prost(message, optional, tag = "3")]
    pub grpc_match_options: ::core::option::Option<GrpcMatchOptions>,
    /// REF: Envoy
    /// Specifies a set of dynamic metadata that a route must match.
    /// The router will check the dynamic metadata against all the specified dynamic metadata matchers.
    /// If the number of specified dynamic metadata matchers is nonzero, they all must match the
    /// dynamic metadata for a match to occur.
    /// TODO -> implement pre 2.0 relase of `fuse`
    #[prost(message, optional, tag = "4")]
    pub dynamic_metadata: ::core::option::Option<DynamicMetadata>,
    /// Host address for the route. May be a literal hostname or a single leading wildcard label
    /// (eg. "\*.draft.localhost") to match any subdomain.
    #[prost(string, tag = "5")]
    pub host: ::prost::alloc::string::String,
    /// Whether `prefix` is matched exactly or as a prefix. Defaults to PREFIX when unset.
    #[prost(enumeration = "MatchType", tag = "6")]
    pub match_type: i32,
}
/// consider using the `key/value` from `blueprint` key/value store
/// TODO -> implement pre 1.0 relase of `fuse`
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeaderMatchOptions {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// GrpcMatchOptions - Options to simplify the matching of a route for grpc. Most request will be grpc and this configuration
/// should make the integration easier.
/// TODO -> implement pre 1.0 relase of `fuse`
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GrpcMatchOptions {}
/// DynamicMetadata - Specifies a set of dynamic metadata that a route must match. Dynamic metadata can be used in a variety of ways
/// and is a powerful feature of envoy `fuse` will most likely use this feature to add additional information to the route.
/// TODO -> implement pre 2.0 relase of `fuse`
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DynamicMetadata {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AddRouteResponseCode {
    InvalidAddRouteResponseCode = 0,
    Ok = 1,
    Error = 2,
    InvalidRequest = 3,
}
impl AddRouteResponseCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::InvalidAddRouteResponseCode => "INVALID_ADD_ROUTE_RESPONSE_CODE",
            Self::Ok => "OK",
            Self::Error => "ERROR",
            Self::InvalidRequest => "INVALID_REQUEST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INVALID_ADD_ROUTE_RESPONSE_CODE" => Some(Self::InvalidAddRouteResponseCode),
            "OK" => Some(Self::Ok),
            "ERROR" => Some(Self::Error),
            "INVALID_REQUEST" => Some(Self::InvalidRequest),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeleteRouteCode {
    InvalidDeleteRouteResponseCode = 0,
    DeleteRouteOk = 1,
    DeleteRouteError = 2,
}
impl DeleteRouteCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::InvalidDeleteRouteResponseCode => "INVALID_DELETE_ROUTE_RESPONSE_CODE",
            Self::DeleteRouteOk => "DELETE_ROUTE_OK",
            Self::DeleteRouteError => "DELETE_ROUTE_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INVALID_DELETE_ROUTE_RESPONSE_CODE" => {
                Some(Self::InvalidDeleteRouteResponseCode)
            }
            "DELETE_ROUTE_OK" => Some(Self::DeleteRouteOk),
            "DELETE_ROUTE_ERROR" => Some(Self::DeleteRouteError),
            _ => None,
        }
    }
}
/// AuthPolicy controls how Fuse configures the Envoy ext_authz filter for a route.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AuthPolicy {
    /// No auth check — route is public.
    Bypass = 0,
    /// Any valid token is accepted.
    Authenticated = 1,
    /// Token must belong to one of the required_groups.
    Groups = 2,
    /// Token must carry all of the required_scopes.
    Scopes = 3,
}
impl AuthPolicy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Bypass => "AUTH_POLICY_BYPASS",
            Self::Authenticated => "AUTH_POLICY_AUTHENTICATED",
            Self::Groups => "AUTH_POLICY_GROUPS",
            Self::Scopes => "AUTH_POLICY_SCOPES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUTH_POLICY_BYPASS" => Some(Self::Bypass),
            "AUTH_POLICY_AUTHENTICATED" => Some(Self::Authenticated),
            "AUTH_POLICY_GROUPS" => Some(Self::Groups),
            "AUTH_POLICY_SCOPES" => Some(Self::Scopes),
            _ => None,
        }
    }
}
/// MatchType controls whether `RouteMatch.prefix` is compiled to an Envoy exact-path match or a
/// prefix match. MATCH_TYPE_UNSPECIFIED is treated as MATCH_TYPE_PREFIX — this matches the runtime
/// behavior every route compiled to before this field existed, so already-registered services keep
/// working unchanged. New callers should set MATCH_TYPE_EXACT explicitly; UNSPECIFIED defaulting to
/// PREFIX is a deliberate backward-compatibility shim, not the intended long-term default.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MatchType {
    Unspecified = 0,
    Exact = 1,
    Prefix = 2,
}
impl MatchType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MATCH_TYPE_UNSPECIFIED",
            Self::Exact => "MATCH_TYPE_EXACT",
            Self::Prefix => "MATCH_TYPE_PREFIX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MATCH_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MATCH_TYPE_EXACT" => Some(Self::Exact),
            "MATCH_TYPE_PREFIX" => Some(Self::Prefix),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod networking_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// An interface to modify the networking configuration of the system. The networking configuration is primarly used to
    /// make endpoints available outside of the system (public, or private). To efficiently route traffic to the correct process, the
    /// networking configuration is used to configure the `Envoy` proxy. The `Envoy` proxy is used to route traffic to the correct process
    /// based on the provided `Route` configuration when the process registers to the system in this case `fuse`.
    ///
    /// 1. The `NetworkingService` is a `core` service implemented in `fuse`
    /// 1. Alot of the networking configuration is specific for `Envoy`. The `Route` proto is an example of this. It's basically a one to one mapping
    ///   of all fields that can't already be inferred by the `draft` framework.
    #[derive(Debug, Clone)]
    pub struct NetworkingServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> NetworkingServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> NetworkingServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            NetworkingServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Add route exposing an endpoint on the gateway and routing traffic to the correct process
        pub async fn add_route(
            &mut self,
            request: impl tonic::IntoRequest<super::AddRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddRouteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core.control_plane.networking.v1.NetworkingService/AddRoute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "core.control_plane.networking.v1.NetworkingService",
                        "AddRoute",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List all routes in the networking configuration
        pub async fn list_routes(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRoutesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListRoutesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core.control_plane.networking.v1.NetworkingService/ListRoutes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "core.control_plane.networking.v1.NetworkingService",
                        "ListRoutes",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Delete a route from the networking configuration, requires the name of the route
        /// and returns a response code to indicate the success of the operation
        pub async fn delete_route(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteRouteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core.control_plane.networking.v1.NetworkingService/DeleteRoute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "core.control_plane.networking.v1.NetworkingService",
                        "DeleteRoute",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Validate a route against the existing networking configuration without persisting it.
        /// Used to surface conflicts (eg. in the blueprint UI) before a route is actually added.
        pub async fn validate_route(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateRouteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core.control_plane.networking.v1.NetworkingService/ValidateRoute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "core.control_plane.networking.v1.NetworkingService",
                        "ValidateRoute",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
