// This file is @generated by prost-build.
/// LogRecord mirrors the `beacon.logs` ClickHouse row (see services/core/beacon/store)
/// which in turn mirrors OTel semantic conventions directly — field names are lifted
/// from the OTLP LogRecord/Resource protos rather than invented, so no translation
/// layer is needed between ingestion and query.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogRecord {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub severity_text: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub severity_number: u32,
    #[prost(string, tag = "6")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub body: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "8")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string", tag = "9")]
    pub resource_attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryLogsRequest {
    /// BeaconQL filter expression, e.g. `severity_text = "ERROR" AND service_name = "beacon"`.
    /// Empty string means no filter — return the most recent rows unfiltered.
    #[prost(string, tag = "1")]
    pub filter: ::prost::alloc::string::String,
    /// Maximum rows to return. 0 = server default (see query/logs.go).
    #[prost(int32, tag = "2")]
    pub limit: i32,
    /// RFC3339 timestamp cursor — only rows strictly after this timestamp are returned.
    /// Empty string means no lower bound.
    #[prost(string, tag = "3")]
    pub after: ::prost::alloc::string::String,
    /// RFC3339 timestamp cursor — only rows strictly before this timestamp are returned.
    /// Empty string means no upper bound. Combined with `after`, bounds both ends of a
    /// custom time range; used alone (with `ascending = false`, the default) it returns
    /// the rows immediately preceding a cursor — e.g. a log detail view's "context before".
    #[prost(string, tag = "4")]
    pub before: ::prost::alloc::string::String,
    /// Sort order. false (default) = most-recent-first (descending), matching QueryLogs'
    /// existing behavior. true = oldest-first (ascending) — needed to correctly return the
    /// rows immediately *after* a cursor (with `after` set) rather than the current tail.
    #[prost(bool, tag = "5")]
    pub ascending: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryLogsResponse {
    #[prost(message, repeated, tag = "1")]
    pub records: ::prost::alloc::vec::Vec<LogRecord>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamLogsRequest {
    /// BeaconQL filter expression; empty means no filter.
    #[prost(string, tag = "1")]
    pub filter: ::prost::alloc::string::String,
    /// Caps the number of historical rows replayed before switching to live tail.
    /// 0 = server default.
    #[prost(int32, tag = "2")]
    pub limit: i32,
    /// RFC3339 timestamp cursor to begin historical replay after. Empty means
    /// "start from the server default lookback window".
    #[prost(string, tag = "3")]
    pub after: ::prost::alloc::string::String,
}
/// One record per stream message so the web client can render each line as it
/// arrives rather than waiting for a batch.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamLogsResponse {
    #[prost(message, optional, tag = "1")]
    pub record: ::core::option::Option<LogRecord>,
}
/// Generated client implementations.
pub mod logs_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ─── Logs Service ─────────────────────────────────────────────────────────────
    ///
    /// LogsService is Beacon's client-facing query surface for log data ingested over
    /// OTLP (see the OTLP LogsService receiver in services/core/beacon/ingest). It is
    /// deliberately separate from the OTLP receiver: OTLP is the standard ingestion
    /// protocol any exporter speaks, LogsService is the Connect-RPC surface the Dioxus
    /// web client (and any other Beacon consumer) queries against.
    #[derive(Debug, Clone)]
    pub struct LogsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> LogsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> LogsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            LogsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// QueryLogs returns a bounded set of log rows matching an optional BeaconQL
        /// filter expression, most recent first by default. `after`/`before` bound
        /// either or both ends of the timestamp range; `ascending` controls sort order.
        pub async fn query_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core.observability.logs.v1.LogsService/QueryLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "core.observability.logs.v1.LogsService",
                        "QueryLogs",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// StreamLogs opens a persistent server-streaming RPC. The server first replays
        /// historical rows matching `filter` (bounded by `limit`, optionally starting
        /// after the `after` cursor), then continues streaming newly-ingested rows
        /// matching the same filter as they arrive. The stream stays open until the
        /// client closes it; the client re-issues the RPC with a new `filter` to change
        /// the active filter, using the last received row's timestamp as the new
        /// `after` cursor so no rows are missed or duplicated across the switch.
        pub async fn stream_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StreamLogsResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core.observability.logs.v1.LogsService/StreamLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "core.observability.logs.v1.LogsService",
                        "StreamLogs",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
