// This file is @generated by prost-build.
/// TraceRoot mirrors one row of the `trace_roots` materialized view (see
/// services/core/beacon/store) — the root span (parent_span_id = "") of a
/// trace, used to populate the Traces view's search-result list without
/// scanning every span of every trace.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TraceRoot {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub span_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "5")]
    pub duration_ns: u64,
    #[prost(string, tag = "6")]
    pub status_code: ::prost::alloc::string::String,
}
/// Span mirrors one row of the `spans` table (see services/core/beacon/store)
/// which in turn mirrors OTel semantic conventions directly — field names are
/// lifted from the OTLP Span proto rather than invented.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Span {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parent_span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub span_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub kind: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "8")]
    pub duration_ns: u64,
    #[prost(string, tag = "9")]
    pub status_code: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "10")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchTracesRequest {
    /// BeaconQL filter expression evaluated against trace_roots's columns,
    /// e.g. `duration_ms > 200 AND service_name = "beacon"`. `duration_ms` is
    /// a synthetic field — trace_roots stores duration_ns, the filter compiler
    /// scales the literal for ergonomics (see CompileTraceRoot). Empty string
    /// means no filter — return the most recent traces unfiltered.
    #[prost(string, tag = "1")]
    pub filter: ::prost::alloc::string::String,
    /// Maximum rows to return. 0 = server default (see store/clickhouse.go).
    #[prost(int32, tag = "2")]
    pub limit: i32,
    /// RFC3339 timestamp cursor — only traces with start_time strictly before
    /// this value are returned, for backward pagination through results
    /// ordered most-recent-first. Empty string means no cursor.
    #[prost(string, tag = "3")]
    pub before: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchTracesResponse {
    #[prost(message, repeated, tag = "1")]
    pub traces: ::prost::alloc::vec::Vec<TraceRoot>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTraceRequest {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTraceResponse {
    #[prost(message, repeated, tag = "1")]
    pub spans: ::prost::alloc::vec::Vec<Span>,
}
/// Generated client implementations.
pub mod traces_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ─── Traces Service ─────────────────────────────────────────────────────────
    ///
    /// TracesService is Beacon's client-facing query surface for trace/span data
    /// ingested over OTLP (see the OTLP TraceService receiver in
    /// services/core/beacon/ingest). It is deliberately separate from the OTLP
    /// receiver: OTLP is the standard ingestion protocol any exporter speaks,
    /// TracesService is the Connect-RPC surface the Dioxus web client (and any
    /// other Beacon consumer) queries against.
    #[derive(Debug, Clone)]
    pub struct TracesServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> TracesServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TracesServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TracesServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// SearchTraces returns a bounded, paginated set of trace roots matching an
        /// optional BeaconQL filter expression (compiled against the `trace_roots`
        /// materialized view's columns — see query/beaconql.go's CompileTraceRoot),
        /// most recent first.
        pub async fn search_traces(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchTracesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchTracesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core.observability.traces.v1.TracesService/SearchTraces",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "core.observability.traces.v1.TracesService",
                        "SearchTraces",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GetTrace returns every span belonging to one trace_id, ordered so a
        /// flame graph can be assembled from parent/child relationships (by
        /// start_time ascending, so a parent always precedes its children).
        pub async fn get_trace(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTraceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTraceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/core.observability.traces.v1.TracesService/GetTrace",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "core.observability.traces.v1.TracesService",
                        "GetTrace",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
