#[path = "./core.message_broker.actors.v1.rs"]
pub mod core_message_broker_actors_v1;
#[path = "./core.registry.service_discovery.v1.rs"]
pub mod core_registry_service_discovery_v1;
#[path = "./core.observability.wide_events.v1.rs"]
pub mod core_observability_wide_events_v1;
#[path = "./core.control_plane.networking.v1.rs"]
pub mod core_control_plane_networking_v1;
#[path = "./core.observability.logs.v1.rs"]
pub mod core_observability_logs_v1;
#[path = "./core.registry.key_value.v1.rs"]
pub mod core_registry_key_value_v1;
#[path = "./core.observability.traces.v1.rs"]
pub mod core_observability_traces_v1;
#[path = "./core.observability.metrics.v1.rs"]
pub mod core_observability_metrics_v1;
