// This file is @generated by prost-build.
/// Objective is a goal a set of tasks count toward. It owns its own ordered
/// list of valid task states -- states are not a global enum shared by every
/// objective (see docs/architecture/lineman-implementation-plan.md's
/// Decisions).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Objective {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// Ordered; e.g. \["Queued", "In Flight", "Verifying", "Done"\]. A Task's
    /// state must be a member of its own objective's states.
    #[prost(string, repeated, tag = "4")]
    pub states: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// NeedsInput is set on a Task only while it's in the objective's
/// "Needs Input"-convention state -- a recommendation, not a hardcoded state
/// name (see the implementation plan's Decisions).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NeedsInput {
    #[prost(string, tag = "1")]
    pub question: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub requested_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Task is a unit of work belonging to exactly one objective, or none
/// (standalone -- objective_id left empty).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Task {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub objective_id: ::prost::alloc::string::String,
    /// Short label -- what shows on a board card. Was "description" (same
    /// wire tag 3, renamed in place -- see the implementation plan's
    /// Decisions for why this was wire-compatible rather than a fresh tag).
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub state: ::prost::alloc::string::String,
    #[prost(enumeration = "Priority", tag = "5")]
    pub priority: i32,
    /// Sparse ordering within (objective_id, state) -- see Decisions.
    #[prost(int64, tag = "6")]
    pub order: i64,
    #[prost(string, tag = "7")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub current_action: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub needs_input: ::core::option::Option<NeedsInput>,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Everything needed to actually complete the task -- free-text
    /// instructions, the primary content a human or agent reads. Optional:
    /// may be empty (e.g. for a task spawned by a ScheduledTask/Loop, which
    /// only ever supply a name -- see Decisions).
    #[prost(string, tag = "12")]
    pub details: ::prost::alloc::string::String,
}
/// Agent is a loose, assignable-worker identity -- a human, a script, or an
/// AI agent instance/run. Not a handle into any other system.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Agent {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(enumeration = "AgentKind", tag = "3")]
    pub kind: i32,
    #[prost(message, optional, tag = "4")]
    pub last_seen_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// ScheduledTask is the Scheduler primitive: fire a single task once, at a
/// specific future time.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduledTask {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub objective_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "Priority", tag = "4")]
    pub priority: i32,
    #[prost(message, optional, tag = "5")]
    pub fire_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "ScheduledTaskStatus", tag = "6")]
    pub status: i32,
    #[prost(string, tag = "7")]
    pub created_task_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Recurrence {
    /// "daily" | "weekly" | "every_n_days" | "cron" -- matches the Loops
    /// create-form mockup's Repeats options.
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub interval_days: i32,
    #[prost(string, tag = "3")]
    pub cron: ::prost::alloc::string::String,
    /// "HH:MM", local to the Lineman process
    #[prost(string, tag = "4")]
    pub at: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub starts_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Zero value = "Never". Mutually exclusive with ends_after_occurrences.
    #[prost(message, optional, tag = "6")]
    pub ends_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag = "7")]
    pub ends_after_occurrences: i32,
}
/// Loop is the recurring primitive: one definition spawns a new Task instance
/// every time it fires.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Loop {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub objective_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "Priority", tag = "4")]
    pub priority: i32,
    #[prost(message, optional, tag = "5")]
    pub recurrence: ::core::option::Option<Recurrence>,
    #[prost(enumeration = "LoopStatus", tag = "6")]
    pub status: i32,
    #[prost(message, optional, tag = "7")]
    pub next_fire_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int64, tag = "8")]
    pub occurrence_count: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Priority {
    Unspecified = 0,
    Low = 1,
    Medium = 2,
    High = 3,
}
impl Priority {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PRIORITY_UNSPECIFIED",
            Self::Low => "PRIORITY_LOW",
            Self::Medium => "PRIORITY_MEDIUM",
            Self::High => "PRIORITY_HIGH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRIORITY_UNSPECIFIED" => Some(Self::Unspecified),
            "PRIORITY_LOW" => Some(Self::Low),
            "PRIORITY_MEDIUM" => Some(Self::Medium),
            "PRIORITY_HIGH" => Some(Self::High),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentKind {
    Unspecified = 0,
    Human = 1,
    Script = 2,
    Ai = 3,
}
impl AgentKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AGENT_KIND_UNSPECIFIED",
            Self::Human => "AGENT_KIND_HUMAN",
            Self::Script => "AGENT_KIND_SCRIPT",
            Self::Ai => "AGENT_KIND_AI",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGENT_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "AGENT_KIND_HUMAN" => Some(Self::Human),
            "AGENT_KIND_SCRIPT" => Some(Self::Script),
            "AGENT_KIND_AI" => Some(Self::Ai),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ScheduledTaskStatus {
    Unspecified = 0,
    Pending = 1,
    Fired = 2,
    Cancelled = 3,
}
impl ScheduledTaskStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SCHEDULED_TASK_STATUS_UNSPECIFIED",
            Self::Pending => "SCHEDULED_TASK_STATUS_PENDING",
            Self::Fired => "SCHEDULED_TASK_STATUS_FIRED",
            Self::Cancelled => "SCHEDULED_TASK_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCHEDULED_TASK_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "SCHEDULED_TASK_STATUS_PENDING" => Some(Self::Pending),
            "SCHEDULED_TASK_STATUS_FIRED" => Some(Self::Fired),
            "SCHEDULED_TASK_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LoopStatus {
    Unspecified = 0,
    Active = 1,
    Paused = 2,
    Finished = 3,
}
impl LoopStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LOOP_STATUS_UNSPECIFIED",
            Self::Active => "LOOP_STATUS_ACTIVE",
            Self::Paused => "LOOP_STATUS_PAUSED",
            Self::Finished => "LOOP_STATUS_FINISHED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOOP_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "LOOP_STATUS_ACTIVE" => Some(Self::Active),
            "LOOP_STATUS_PAUSED" => Some(Self::Paused),
            "LOOP_STATUS_FINISHED" => Some(Self::Finished),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateObjectiveRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// Left empty to default to \["Queued", "In Flight", "Done"\].
    #[prost(string, repeated, tag = "3")]
    pub states: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetObjectiveRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListObjectivesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListObjectivesResponse {
    #[prost(message, repeated, tag = "1")]
    pub objectives: ::prost::alloc::vec::Vec<Objective>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTaskRequest {
    /// empty for a standalone task
    #[prost(string, tag = "1")]
    pub objective_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "Priority", tag = "3")]
    pub priority: i32,
    /// Left empty to default to the objective's first state (or "Queued" for
    /// a standalone task).
    #[prost(string, tag = "4")]
    pub state: ::prost::alloc::string::String,
    /// Everything needed to complete the task -- optional.
    #[prost(string, tag = "5")]
    pub details: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTaskRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTasksRequest {
    /// All filters optional; an unset field means "no filter on this field."
    #[prost(string, tag = "1")]
    pub objective_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub agent_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTasksResponse {
    #[prost(message, repeated, tag = "1")]
    pub tasks: ::prost::alloc::vec::Vec<Task>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTaskStateRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReorderTaskRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// The task's new order value is computed server-side as the midpoint
    /// between before_task_id's and after_task_id's current order (either
    /// may be empty to mean "start"/"end" of the list).
    #[prost(string, tag = "2")]
    pub before_task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub after_task_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignAgentRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// empty to unassign
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatRequest {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    /// used only the first time agent_id is seen
    #[prost(string, tag = "2")]
    pub agent_display_name: ::prost::alloc::string::String,
    /// used only the first time agent_id is seen
    #[prost(enumeration = "AgentKind", tag = "3")]
    pub agent_kind: i32,
    #[prost(string, tag = "4")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub current_action: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListAgentsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAgentsResponse {
    #[prost(message, repeated, tag = "1")]
    pub agents: ::prost::alloc::vec::Vec<Agent>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestInputRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub question: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProvideGuidanceRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub response: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub next_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateScheduledTaskRequest {
    #[prost(string, tag = "1")]
    pub objective_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "Priority", tag = "3")]
    pub priority: i32,
    #[prost(message, optional, tag = "4")]
    pub fire_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListScheduledTasksRequest {
    /// optional filter
    #[prost(string, tag = "1")]
    pub objective_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListScheduledTasksResponse {
    #[prost(message, repeated, tag = "1")]
    pub scheduled_tasks: ::prost::alloc::vec::Vec<ScheduledTask>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelScheduledTaskRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelScheduledTaskResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateLoopRequest {
    #[prost(string, tag = "1")]
    pub objective_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "Priority", tag = "3")]
    pub priority: i32,
    #[prost(message, optional, tag = "4")]
    pub recurrence: ::core::option::Option<Recurrence>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListLoopsRequest {
    /// optional filter
    #[prost(string, tag = "1")]
    pub objective_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListLoopsResponse {
    #[prost(message, repeated, tag = "1")]
    pub loops: ::prost::alloc::vec::Vec<Loop>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PauseLoopRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResumeLoopRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteLoopRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteLoopResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchResponse {
    #[prost(bool, tag = "5")]
    pub removed: bool,
    #[prost(oneof = "watch_response::Item", tags = "1, 2, 3, 4")]
    pub item: ::core::option::Option<watch_response::Item>,
}
/// Nested message and enum types in `WatchResponse`.
pub mod watch_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Item {
        #[prost(message, tag = "1")]
        Task(super::Task),
        #[prost(message, tag = "2")]
        Agent(super::Agent),
        #[prost(message, tag = "3")]
        ScheduledTask(super::ScheduledTask),
        #[prost(message, tag = "4")]
        Loop(super::Loop),
    }
}
/// Generated client implementations.
pub mod lineman_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// LinemanService is Lineman's whole API surface -- objectives, tasks,
    /// agents, the Scheduler and Loops primitives, and a live-update stream. See
    /// docs/architecture/lineman-implementation-plan.md.
    #[derive(Debug, Clone)]
    pub struct LinemanServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> LinemanServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> LinemanServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            LinemanServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Objectives
        pub async fn create_objective(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateObjectiveRequest>,
        ) -> std::result::Result<tonic::Response<super::Objective>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/CreateObjective",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "tooling.lineman.v1.LinemanService",
                        "CreateObjective",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_objective(
            &mut self,
            request: impl tonic::IntoRequest<super::GetObjectiveRequest>,
        ) -> std::result::Result<tonic::Response<super::Objective>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/GetObjective",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "GetObjective"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_objectives(
            &mut self,
            request: impl tonic::IntoRequest<super::ListObjectivesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListObjectivesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/ListObjectives",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "tooling.lineman.v1.LinemanService",
                        "ListObjectives",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Tasks
        pub async fn create_task(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateTaskRequest>,
        ) -> std::result::Result<tonic::Response<super::Task>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/CreateTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "CreateTask"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_task(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTaskRequest>,
        ) -> std::result::Result<tonic::Response<super::Task>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/GetTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tooling.lineman.v1.LinemanService", "GetTask"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_tasks(
            &mut self,
            request: impl tonic::IntoRequest<super::ListTasksRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTasksResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/ListTasks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "ListTasks"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_task_state(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateTaskStateRequest>,
        ) -> std::result::Result<tonic::Response<super::Task>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/UpdateTaskState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "tooling.lineman.v1.LinemanService",
                        "UpdateTaskState",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn reorder_task(
            &mut self,
            request: impl tonic::IntoRequest<super::ReorderTaskRequest>,
        ) -> std::result::Result<tonic::Response<super::Task>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/ReorderTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "ReorderTask"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn assign_agent(
            &mut self,
            request: impl tonic::IntoRequest<super::AssignAgentRequest>,
        ) -> std::result::Result<tonic::Response<super::Task>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/AssignAgent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "AssignAgent"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Agents -- called by whatever is doing the work (human tooling, a
        /// script, or an AI agent run), not by Lineman's own UI.
        pub async fn heartbeat(
            &mut self,
            request: impl tonic::IntoRequest<super::HeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HeartbeatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/Heartbeat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "Heartbeat"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_agents(
            &mut self,
            request: impl tonic::IntoRequest<super::ListAgentsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAgentsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/ListAgents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "ListAgents"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Needs Input -- the recommended human-in-the-loop convention.
        pub async fn request_input(
            &mut self,
            request: impl tonic::IntoRequest<super::RequestInputRequest>,
        ) -> std::result::Result<tonic::Response<super::Task>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/RequestInput",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "RequestInput"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn provide_guidance(
            &mut self,
            request: impl tonic::IntoRequest<super::ProvideGuidanceRequest>,
        ) -> std::result::Result<tonic::Response<super::Task>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/ProvideGuidance",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "tooling.lineman.v1.LinemanService",
                        "ProvideGuidance",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Scheduler
        pub async fn create_scheduled_task(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateScheduledTaskRequest>,
        ) -> std::result::Result<tonic::Response<super::ScheduledTask>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/CreateScheduledTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "tooling.lineman.v1.LinemanService",
                        "CreateScheduledTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_scheduled_tasks(
            &mut self,
            request: impl tonic::IntoRequest<super::ListScheduledTasksRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListScheduledTasksResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/ListScheduledTasks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "tooling.lineman.v1.LinemanService",
                        "ListScheduledTasks",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_scheduled_task(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelScheduledTaskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelScheduledTaskResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/CancelScheduledTask",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "tooling.lineman.v1.LinemanService",
                        "CancelScheduledTask",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Loops
        pub async fn create_loop(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateLoopRequest>,
        ) -> std::result::Result<tonic::Response<super::Loop>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/CreateLoop",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "CreateLoop"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_loops(
            &mut self,
            request: impl tonic::IntoRequest<super::ListLoopsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLoopsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/ListLoops",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "ListLoops"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn pause_loop(
            &mut self,
            request: impl tonic::IntoRequest<super::PauseLoopRequest>,
        ) -> std::result::Result<tonic::Response<super::Loop>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/PauseLoop",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "PauseLoop"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn resume_loop(
            &mut self,
            request: impl tonic::IntoRequest<super::ResumeLoopRequest>,
        ) -> std::result::Result<tonic::Response<super::Loop>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/ResumeLoop",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "ResumeLoop"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_loop(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteLoopRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteLoopResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/DeleteLoop",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("tooling.lineman.v1.LinemanService", "DeleteLoop"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Live board updates -- mirrors ServiceDiscoveryService.Watch, not a
        /// Catalyst Consume subscription (see Decisions: fan-out bug).
        pub async fn watch(
            &mut self,
            request: impl tonic::IntoRequest<super::WatchRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::WatchResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tooling.lineman.v1.LinemanService/Watch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tooling.lineman.v1.LinemanService", "Watch"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
