// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: examples/echo/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message" bun:"message" csv:"message" pg:"message" yaml:"message"`
	Sender  string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender" bun:"sender" csv:"sender" pg:"sender" yaml:"sender"`
}

func (x *HelloWorld) Reset() {
	*x = HelloWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_echo_v1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorld) ProtoMessage() {}

func (x *HelloWorld) ProtoReflect() protoreflect.Message {
	mi := &file_examples_echo_v1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorld.ProtoReflect.Descriptor instead.
func (*HelloWorld) Descriptor() ([]byte, []int) {
	return file_examples_echo_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *HelloWorld) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloWorld) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bun:"id" csv:"id" pg:"id" yaml:"id"`
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender" bun:"sender" csv:"sender" pg:"sender" yaml:"sender"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_echo_v1_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_examples_echo_v1_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_examples_echo_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ping) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PingId    string `protobuf:"bytes,1,opt,name=ping_id,json=pingId,proto3" json:"ping_id" bun:"ping_id" csv:"ping_id" pg:"ping_id" yaml:"ping_id"`
	Responder string `protobuf:"bytes,2,opt,name=responder,proto3" json:"responder" bun:"responder" csv:"responder" pg:"responder" yaml:"responder"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_echo_v1_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_examples_echo_v1_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_examples_echo_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *Pong) GetPingId() string {
	if x != nil {
		return x.PingId
	}
	return ""
}

func (x *Pong) GetResponder() string {
	if x != nil {
		return x.Responder
	}
	return ""
}

var File_examples_echo_v1_events_proto protoreflect.FileDescriptor

var file_examples_echo_v1_events_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76,
	0x31, 0x22, 0x3e, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x22, 0x2e, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x22, 0x3d, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x69, 0x6e, 0x67,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x74, 0x65, 0x61, 0x64, 0x79, 0x2d, 0x62, 0x79, 0x74, 0x65, 0x73, 0x2f, 0x64, 0x72, 0x61, 0x66,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x65,
	0x63, 0x68, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examples_echo_v1_events_proto_rawDescOnce sync.Once
	file_examples_echo_v1_events_proto_rawDescData = file_examples_echo_v1_events_proto_rawDesc
)

func file_examples_echo_v1_events_proto_rawDescGZIP() []byte {
	file_examples_echo_v1_events_proto_rawDescOnce.Do(func() {
		file_examples_echo_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_echo_v1_events_proto_rawDescData)
	})
	return file_examples_echo_v1_events_proto_rawDescData
}

var file_examples_echo_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_echo_v1_events_proto_goTypes = []any{
	(*HelloWorld)(nil), // 0: examples.echo.v1.HelloWorld
	(*Ping)(nil),       // 1: examples.echo.v1.Ping
	(*Pong)(nil),       // 2: examples.echo.v1.Pong
}
var file_examples_echo_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_echo_v1_events_proto_init() }
func file_examples_echo_v1_events_proto_init() {
	if File_examples_echo_v1_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examples_echo_v1_events_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HelloWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_echo_v1_events_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_echo_v1_events_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_echo_v1_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_echo_v1_events_proto_goTypes,
		DependencyIndexes: file_examples_echo_v1_events_proto_depIdxs,
		MessageInfos:      file_examples_echo_v1_events_proto_msgTypes,
	}.Build()
	File_examples_echo_v1_events_proto = out.File
	file_examples_echo_v1_events_proto_rawDesc = nil
	file_examples_echo_v1_events_proto_goTypes = nil
	file_examples_echo_v1_events_proto_depIdxs = nil
}
