// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/echo/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpeakRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakRequest) Reset() {
	*x = SpeakRequest{}
	mi := &file_examples_echo_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakRequest) ProtoMessage() {}

func (x *SpeakRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_echo_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakRequest.ProtoReflect.Descriptor instead.
func (*SpeakRequest) Descriptor() ([]byte, []int) {
	return file_examples_echo_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SpeakRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type SpeakResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakResponse) Reset() {
	*x = SpeakResponse{}
	mi := &file_examples_echo_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakResponse) ProtoMessage() {}

func (x *SpeakResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_echo_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakResponse.ProtoReflect.Descriptor instead.
func (*SpeakResponse) Descriptor() ([]byte, []int) {
	return file_examples_echo_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SpeakResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_examples_echo_v1_service_proto protoreflect.FileDescriptor

const file_examples_echo_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1eexamples/echo/v1/service.proto\x12\x10examples.echo.v1\"$\n" +
	"\fSpeakRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"'\n" +
	"\rSpeakResponse\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output2Y\n" +
	"\vEchoService\x12J\n" +
	"\x05Speak\x12\x1e.examples.echo.v1.SpeakRequest\x1a\x1f.examples.echo.v1.SpeakResponse\"\x00B4Z2github.com/steady-bytes/draft/api/examples/echo/v1b\x06proto3"

var (
	file_examples_echo_v1_service_proto_rawDescOnce sync.Once
	file_examples_echo_v1_service_proto_rawDescData []byte
)

func file_examples_echo_v1_service_proto_rawDescGZIP() []byte {
	file_examples_echo_v1_service_proto_rawDescOnce.Do(func() {
		file_examples_echo_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_echo_v1_service_proto_rawDesc), len(file_examples_echo_v1_service_proto_rawDesc)))
	})
	return file_examples_echo_v1_service_proto_rawDescData
}

var file_examples_echo_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_echo_v1_service_proto_goTypes = []any{
	(*SpeakRequest)(nil),  // 0: examples.echo.v1.SpeakRequest
	(*SpeakResponse)(nil), // 1: examples.echo.v1.SpeakResponse
}
var file_examples_echo_v1_service_proto_depIdxs = []int32{
	0, // 0: examples.echo.v1.EchoService.Speak:input_type -> examples.echo.v1.SpeakRequest
	1, // 1: examples.echo.v1.EchoService.Speak:output_type -> examples.echo.v1.SpeakResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_echo_v1_service_proto_init() }
func file_examples_echo_v1_service_proto_init() {
	if File_examples_echo_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_echo_v1_service_proto_rawDesc), len(file_examples_echo_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_echo_v1_service_proto_goTypes,
		DependencyIndexes: file_examples_echo_v1_service_proto_depIdxs,
		MessageInfos:      file_examples_echo_v1_service_proto_msgTypes,
	}.Build()
	File_examples_echo_v1_service_proto = out.File
	file_examples_echo_v1_service_proto_goTypes = nil
	file_examples_echo_v1_service_proto_depIdxs = nil
}
