// @generated by protoc-gen-connect-query v1.1.3 with parameter "target=ts"
// @generated from file examples/echo/v1/service.proto (package examples.echo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { SpeakRequest, SpeakResponse } from "./service_pb.js";

/**
 * @generated from rpc examples.echo.v1.EchoService.Speak
 */
export const speak = {
  localName: "speak",
  name: "Speak",
  kind: MethodKind.Unary,
  I: SpeakRequest,
  O: SpeakResponse,
  service: {
    typeName: "examples.echo.v1.EchoService"
  }
} as const;
