// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/message_broker/actors/v1/resource_metrics.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/steady-bytes/draft/api/core/message_broker/actors/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResourceMetricsName is the fully-qualified name of the ResourceMetrics service.
	ResourceMetricsName = "core.message_broker.actors.v1.ResourceMetrics"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResourceMetricsGetResourceMetricsProcedure is the fully-qualified name of the ResourceMetrics's
	// GetResourceMetrics RPC.
	ResourceMetricsGetResourceMetricsProcedure = "/core.message_broker.actors.v1.ResourceMetrics/GetResourceMetrics"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	resourceMetricsServiceDescriptor                  = v1.File_core_message_broker_actors_v1_resource_metrics_proto.Services().ByName("ResourceMetrics")
	resourceMetricsGetResourceMetricsMethodDescriptor = resourceMetricsServiceDescriptor.Methods().ByName("GetResourceMetrics")
)

// ResourceMetricsClient is a client for the core.message_broker.actors.v1.ResourceMetrics service.
type ResourceMetricsClient interface {
	GetResourceMetrics(context.Context, *connect.Request[v1.GetResourceMetricsRequest]) (*connect.Response[v1.GetResourceMetricsResponse], error)
}

// NewResourceMetricsClient constructs a client for the
// core.message_broker.actors.v1.ResourceMetrics service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResourceMetricsClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResourceMetricsClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &resourceMetricsClient{
		getResourceMetrics: connect.NewClient[v1.GetResourceMetricsRequest, v1.GetResourceMetricsResponse](
			httpClient,
			baseURL+ResourceMetricsGetResourceMetricsProcedure,
			connect.WithSchema(resourceMetricsGetResourceMetricsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// resourceMetricsClient implements ResourceMetricsClient.
type resourceMetricsClient struct {
	getResourceMetrics *connect.Client[v1.GetResourceMetricsRequest, v1.GetResourceMetricsResponse]
}

// GetResourceMetrics calls core.message_broker.actors.v1.ResourceMetrics.GetResourceMetrics.
func (c *resourceMetricsClient) GetResourceMetrics(ctx context.Context, req *connect.Request[v1.GetResourceMetricsRequest]) (*connect.Response[v1.GetResourceMetricsResponse], error) {
	return c.getResourceMetrics.CallUnary(ctx, req)
}

// ResourceMetricsHandler is an implementation of the core.message_broker.actors.v1.ResourceMetrics
// service.
type ResourceMetricsHandler interface {
	GetResourceMetrics(context.Context, *connect.Request[v1.GetResourceMetricsRequest]) (*connect.Response[v1.GetResourceMetricsResponse], error)
}

// NewResourceMetricsHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResourceMetricsHandler(svc ResourceMetricsHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resourceMetricsGetResourceMetricsHandler := connect.NewUnaryHandler(
		ResourceMetricsGetResourceMetricsProcedure,
		svc.GetResourceMetrics,
		connect.WithSchema(resourceMetricsGetResourceMetricsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.message_broker.actors.v1.ResourceMetrics/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResourceMetricsGetResourceMetricsProcedure:
			resourceMetricsGetResourceMetricsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResourceMetricsHandler returns CodeUnimplemented from all methods.
type UnimplementedResourceMetricsHandler struct{}

func (UnimplementedResourceMetricsHandler) GetResourceMetrics(context.Context, *connect.Request[v1.GetResourceMetricsRequest]) (*connect.Response[v1.GetResourceMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.message_broker.actors.v1.ResourceMetrics.GetResourceMetrics is not implemented"))
}
