service:
  name: fuse
  domain: core
  entrypoint: http://localhost:2221
  advertise_address: 127.0.0.1
  network:
    port: 18000

fuse:
  address: http://localhost:18000
  listener:
    address: 0.0.0.0
    port: 10000