service:
  name: fuse
  domain: core
  entrypoint: http://localhost:2221

  logging:
    level: debug

  network:
    bind_port: 18000
    internal:
      host: localhost
      port: 18000

fuse:
  address: http://localhost:18000
  listener:
    address: localhost
    port: 10000
