service:
  name: file_host
  domain: examples
  env: local
  entrypoint: http://localhost:2221
  logging:
    level: debug

  network:
    bind_address: localhost
    bind_port: 9092
    internal:
      host: host.docker.internal
      port: 9092
    external:
      host: localhost:10000
