// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/registry/service_discovery/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeadershipStatus int32

const (
	LeadershipStatus_LEADERSHIP_STATUS_UNSPECIFIED LeadershipStatus = 0
	LeadershipStatus_LEADERSHIP_STATUS_LEADER      LeadershipStatus = 1
	LeadershipStatus_LEADERSHIP_STATUS_FOLLOWER    LeadershipStatus = 2
)

// Enum value maps for LeadershipStatus.
var (
	LeadershipStatus_name = map[int32]string{
		0: "LEADERSHIP_STATUS_UNSPECIFIED",
		1: "LEADERSHIP_STATUS_LEADER",
		2: "LEADERSHIP_STATUS_FOLLOWER",
	}
	LeadershipStatus_value = map[string]int32{
		"LEADERSHIP_STATUS_UNSPECIFIED": 0,
		"LEADERSHIP_STATUS_LEADER":      1,
		"LEADERSHIP_STATUS_FOLLOWER":    2,
	}
)

func (x LeadershipStatus) Enum() *LeadershipStatus {
	p := new(LeadershipStatus)
	*p = x
	return p
}

func (x LeadershipStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeadershipStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_core_registry_service_discovery_v1_service_proto_enumTypes[0].Descriptor()
}

func (LeadershipStatus) Type() protoreflect.EnumType {
	return &file_core_registry_service_discovery_v1_service_proto_enumTypes[0]
}

func (x LeadershipStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeadershipStatus.Descriptor instead.
func (LeadershipStatus) EnumDescriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{0}
}

// ProcessDetails - Messages that are sent from the `Process` to the registry.
// These details are basic operating messages
type ClientDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pid   string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Ops details
	RunningState ProcessRunningState `protobuf:"varint,2,opt,name=running_state,json=runningState,proto3,enum=core.registry.service_discovery.v1.ProcessRunningState" json:"running_state,omitempty"`
	HealthState  ProcessHealthState  `protobuf:"varint,3,opt,name=health_state,json=healthState,proto3,enum=core.registry.service_discovery.v1.ProcessHealthState" json:"health_state,omitempty"`
	ProcessKind  ProcessKind         `protobuf:"varint,4,opt,name=process_kind,json=processKind,proto3,enum=core.registry.service_discovery.v1.ProcessKind" json:"process_kind,omitempty"`
	// only check the token when a `ProcessDetails` message is received.
	Token            string      `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Location         *GeoPoint   `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Metadata         []*Metadata `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty"`
	AdvertiseAddress string      `protobuf:"bytes,9,opt,name=advertise_address,json=advertiseAddress,proto3" json:"advertise_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientDetails) Reset() {
	*x = ClientDetails{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDetails) ProtoMessage() {}

func (x *ClientDetails) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDetails.ProtoReflect.Descriptor instead.
func (*ClientDetails) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClientDetails) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ClientDetails) GetRunningState() ProcessRunningState {
	if x != nil {
		return x.RunningState
	}
	return ProcessRunningState_INVALID_PROCESS_RUNNING_STATE
}

func (x *ClientDetails) GetHealthState() ProcessHealthState {
	if x != nil {
		return x.HealthState
	}
	return ProcessHealthState_INVALID_PROCESS_HEALTH_STATE
}

func (x *ClientDetails) GetProcessKind() ProcessKind {
	if x != nil {
		return x.ProcessKind
	}
	return ProcessKind_INVALID_PROCESS_KIND
}

func (x *ClientDetails) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ClientDetails) GetLocation() *GeoPoint {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ClientDetails) GetMetadata() []*Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClientDetails) GetAdvertiseAddress() string {
	if x != nil {
		return x.AdvertiseAddress
	}
	return ""
}

type ClusterDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterDetails) Reset() {
	*x = ClusterDetails{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterDetails) ProtoMessage() {}

func (x *ClusterDetails) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterDetails.ProtoReflect.Descriptor instead.
func (*ClusterDetails) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterDetails) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Node struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LeadershipStatus LeadershipStatus       `protobuf:"varint,3,opt,name=leadership_status,json=leadershipStatus,proto3,enum=core.registry.service_discovery.v1.LeadershipStatus" json:"leadership_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Node) GetLeadershipStatus() LeadershipStatus {
	if x != nil {
		return x.LeadershipStatus
	}
	return LeadershipStatus_LEADERSHIP_STATUS_UNSPECIFIED
}

// InitRequest - Begin the service registry registration flow.
type InitializeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the process to be registered. This field is not required to be unique with the other processes in the registry
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A token will not be issued, and a process will not be able to connect to the `SystemJournal` if the `nonce` is not signed with the correct public key
	Nonce         string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *InitializeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitializeRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// InitResponse - Details used by the client to provided to complete the connection
// If the token is lost and the registry has not received a `ProcessDetails` message within a 2 mintues
// of the token being forged then the client will have to reinit to connect to the registry/system.
type InitializeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If the init request was succesful then an identity will be given to the process so that it
	// can stream it's operational details to the registry
	ProcessIdentity *ProcessIdentity `protobuf:"bytes,1,opt,name=process_identity,json=processIdentity,proto3" json:"process_identity,omitempty"`
	// Startup configuration
	Configuration *StartupConfiguration `protobuf:"bytes,2,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeResponse) GetProcessIdentity() *ProcessIdentity {
	if x != nil {
		return x.ProcessIdentity
	}
	return nil
}

func (x *InitializeResponse) GetConfiguration() *StartupConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Attribute:
	//
	//	*Filter_Id
	//	*Filter_Group
	//	*Filter_All
	Attribute     isFilter_Attribute `protobuf_oneof:"attribute"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *Filter) GetAttribute() isFilter_Attribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *Filter) GetId() string {
	if x != nil {
		if x, ok := x.Attribute.(*Filter_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *Filter) GetGroup() string {
	if x != nil {
		if x, ok := x.Attribute.(*Filter_Group); ok {
			return x.Group
		}
	}
	return ""
}

func (x *Filter) GetAll() string {
	if x != nil {
		if x, ok := x.Attribute.(*Filter_All); ok {
			return x.All
		}
	}
	return ""
}

type isFilter_Attribute interface {
	isFilter_Attribute()
}

type Filter_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type Filter_Group struct {
	Group string `protobuf:"bytes,2,opt,name=group,proto3,oneof"`
}

type Filter_All struct {
	All string `protobuf:"bytes,3,opt,name=all,proto3,oneof"`
}

func (*Filter_Id) isFilter_Attribute() {}

func (*Filter_Group) isFilter_Attribute() {}

func (*Filter_All) isFilter_Attribute() {}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]*Process    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *QueryResponse) GetData() map[string]*Process {
	if x != nil {
		return x.Data
	}
	return nil
}

type FinalizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeRequest) Reset() {
	*x = FinalizeRequest{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRequest) ProtoMessage() {}

func (x *FinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRequest.ProtoReflect.Descriptor instead.
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *FinalizeRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type FinalizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeResponse) Reset() {
	*x = FinalizeResponse{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeResponse) ProtoMessage() {}

func (x *FinalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeResponse.ProtoReflect.Descriptor instead.
func (*FinalizeResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *FinalizeResponse) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type ReportHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHealthRequest) Reset() {
	*x = ReportHealthRequest{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHealthRequest) ProtoMessage() {}

func (x *ReportHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHealthRequest.ProtoReflect.Descriptor instead.
func (*ReportHealthRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{10}
}

type ReportHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHealthResponse) Reset() {
	*x = ReportHealthResponse{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHealthResponse) ProtoMessage() {}

func (x *ReportHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHealthResponse.ProtoReflect.Descriptor instead.
func (*ReportHealthResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{11}
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{12}
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *Process               `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Removed       bool                   `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_service_discovery_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_service_discovery_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *WatchResponse) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *WatchResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

var File_core_registry_service_discovery_v1_service_proto protoreflect.FileDescriptor

const file_core_registry_service_discovery_v1_service_proto_rawDesc = "" +
	"\n" +
	"0core/registry/service_discovery/v1/service.proto\x12\"core.registry.service_discovery.v1\x1a/core/registry/service_discovery/v1/models.proto\"\x85\x04\n" +
	"\rClientDetails\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\x12\\\n" +
	"\rrunning_state\x18\x02 \x01(\x0e27.core.registry.service_discovery.v1.ProcessRunningStateR\frunningState\x12Y\n" +
	"\fhealth_state\x18\x03 \x01(\x0e26.core.registry.service_discovery.v1.ProcessHealthStateR\vhealthState\x12R\n" +
	"\fprocess_kind\x18\x04 \x01(\x0e2/.core.registry.service_discovery.v1.ProcessKindR\vprocessKind\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12H\n" +
	"\blocation\x18\a \x01(\v2,.core.registry.service_discovery.v1.GeoPointR\blocation\x12H\n" +
	"\bmetadata\x18\b \x03(\v2,.core.registry.service_discovery.v1.MetadataR\bmetadata\x12+\n" +
	"\x11advertise_address\x18\t \x01(\tR\x10advertiseAddress\"P\n" +
	"\x0eClusterDetails\x12>\n" +
	"\x05nodes\x18\x01 \x03(\v2(.core.registry.service_discovery.v1.NodeR\x05nodes\"\x93\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12a\n" +
	"\x11leadership_status\x18\x03 \x01(\x0e24.core.registry.service_discovery.v1.LeadershipStatusR\x10leadershipStatus\"=\n" +
	"\x11InitializeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\"\xd4\x01\n" +
	"\x12InitializeResponse\x12^\n" +
	"\x10process_identity\x18\x01 \x01(\v23.core.registry.service_discovery.v1.ProcessIdentityR\x0fprocessIdentity\x12^\n" +
	"\rconfiguration\x18\x02 \x01(\v28.core.registry.service_discovery.v1.StartupConfigurationR\rconfiguration\"R\n" +
	"\fQueryRequest\x12B\n" +
	"\x06filter\x18\x01 \x01(\v2*.core.registry.service_discovery.v1.FilterR\x06filter\"S\n" +
	"\x06Filter\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x16\n" +
	"\x05group\x18\x02 \x01(\tH\x00R\x05group\x12\x12\n" +
	"\x03all\x18\x03 \x01(\tH\x00R\x03allB\v\n" +
	"\tattribute\"\xc6\x01\n" +
	"\rQueryResponse\x12O\n" +
	"\x04data\x18\x01 \x03(\v2;.core.registry.service_discovery.v1.QueryResponse.DataEntryR\x04data\x1ad\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.core.registry.service_discovery.v1.ProcessR\x05value:\x028\x01\"#\n" +
	"\x0fFinalizeRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\"$\n" +
	"\x10FinalizeResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\"\x15\n" +
	"\x13ReportHealthRequest\"\x16\n" +
	"\x14ReportHealthResponse\"\x0e\n" +
	"\fWatchRequest\"p\n" +
	"\rWatchResponse\x12E\n" +
	"\aprocess\x18\x01 \x01(\v2+.core.registry.service_discovery.v1.ProcessR\aprocess\x12\x18\n" +
	"\aremoved\x18\x02 \x01(\bR\aremoved*s\n" +
	"\x10LeadershipStatus\x12!\n" +
	"\x1dLEADERSHIP_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18LEADERSHIP_STATUS_LEADER\x10\x01\x12\x1e\n" +
	"\x1aLEADERSHIP_STATUS_FOLLOWER\x10\x022\xf5\x05\n" +
	"\x17ServiceDiscoveryService\x12}\n" +
	"\n" +
	"Initialize\x125.core.registry.service_discovery.v1.InitializeRequest\x1a6.core.registry.service_discovery.v1.InitializeResponse\"\x00\x12z\n" +
	"\vSynchronize\x121.core.registry.service_discovery.v1.ClientDetails\x1a2.core.registry.service_discovery.v1.ClusterDetails\"\x00(\x010\x01\x12w\n" +
	"\bFinalize\x123.core.registry.service_discovery.v1.FinalizeRequest\x1a4.core.registry.service_discovery.v1.FinalizeResponse\"\x00\x12\x83\x01\n" +
	"\fReportHealth\x127.core.registry.service_discovery.v1.ReportHealthRequest\x1a8.core.registry.service_discovery.v1.ReportHealthResponse\"\x00\x12n\n" +
	"\x05Query\x120.core.registry.service_discovery.v1.QueryRequest\x1a1.core.registry.service_discovery.v1.QueryResponse\"\x00\x12p\n" +
	"\x05Watch\x120.core.registry.service_discovery.v1.WatchRequest\x1a1.core.registry.service_discovery.v1.WatchResponse\"\x000\x01BFZDgithub.com/steady-bytes/draft/api/core/registry/service_discovery/v1b\x06proto3"

var (
	file_core_registry_service_discovery_v1_service_proto_rawDescOnce sync.Once
	file_core_registry_service_discovery_v1_service_proto_rawDescData []byte
)

func file_core_registry_service_discovery_v1_service_proto_rawDescGZIP() []byte {
	file_core_registry_service_discovery_v1_service_proto_rawDescOnce.Do(func() {
		file_core_registry_service_discovery_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_registry_service_discovery_v1_service_proto_rawDesc), len(file_core_registry_service_discovery_v1_service_proto_rawDesc)))
	})
	return file_core_registry_service_discovery_v1_service_proto_rawDescData
}

var file_core_registry_service_discovery_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_registry_service_discovery_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_core_registry_service_discovery_v1_service_proto_goTypes = []any{
	(LeadershipStatus)(0),        // 0: core.registry.service_discovery.v1.LeadershipStatus
	(*ClientDetails)(nil),        // 1: core.registry.service_discovery.v1.ClientDetails
	(*ClusterDetails)(nil),       // 2: core.registry.service_discovery.v1.ClusterDetails
	(*Node)(nil),                 // 3: core.registry.service_discovery.v1.Node
	(*InitializeRequest)(nil),    // 4: core.registry.service_discovery.v1.InitializeRequest
	(*InitializeResponse)(nil),   // 5: core.registry.service_discovery.v1.InitializeResponse
	(*QueryRequest)(nil),         // 6: core.registry.service_discovery.v1.QueryRequest
	(*Filter)(nil),               // 7: core.registry.service_discovery.v1.Filter
	(*QueryResponse)(nil),        // 8: core.registry.service_discovery.v1.QueryResponse
	(*FinalizeRequest)(nil),      // 9: core.registry.service_discovery.v1.FinalizeRequest
	(*FinalizeResponse)(nil),     // 10: core.registry.service_discovery.v1.FinalizeResponse
	(*ReportHealthRequest)(nil),  // 11: core.registry.service_discovery.v1.ReportHealthRequest
	(*ReportHealthResponse)(nil), // 12: core.registry.service_discovery.v1.ReportHealthResponse
	(*WatchRequest)(nil),         // 13: core.registry.service_discovery.v1.WatchRequest
	(*WatchResponse)(nil),        // 14: core.registry.service_discovery.v1.WatchResponse
	nil,                          // 15: core.registry.service_discovery.v1.QueryResponse.DataEntry
	(ProcessRunningState)(0),     // 16: core.registry.service_discovery.v1.ProcessRunningState
	(ProcessHealthState)(0),      // 17: core.registry.service_discovery.v1.ProcessHealthState
	(ProcessKind)(0),             // 18: core.registry.service_discovery.v1.ProcessKind
	(*GeoPoint)(nil),             // 19: core.registry.service_discovery.v1.GeoPoint
	(*Metadata)(nil),             // 20: core.registry.service_discovery.v1.Metadata
	(*ProcessIdentity)(nil),      // 21: core.registry.service_discovery.v1.ProcessIdentity
	(*StartupConfiguration)(nil), // 22: core.registry.service_discovery.v1.StartupConfiguration
	(*Process)(nil),              // 23: core.registry.service_discovery.v1.Process
}
var file_core_registry_service_discovery_v1_service_proto_depIdxs = []int32{
	16, // 0: core.registry.service_discovery.v1.ClientDetails.running_state:type_name -> core.registry.service_discovery.v1.ProcessRunningState
	17, // 1: core.registry.service_discovery.v1.ClientDetails.health_state:type_name -> core.registry.service_discovery.v1.ProcessHealthState
	18, // 2: core.registry.service_discovery.v1.ClientDetails.process_kind:type_name -> core.registry.service_discovery.v1.ProcessKind
	19, // 3: core.registry.service_discovery.v1.ClientDetails.location:type_name -> core.registry.service_discovery.v1.GeoPoint
	20, // 4: core.registry.service_discovery.v1.ClientDetails.metadata:type_name -> core.registry.service_discovery.v1.Metadata
	3,  // 5: core.registry.service_discovery.v1.ClusterDetails.nodes:type_name -> core.registry.service_discovery.v1.Node
	0,  // 6: core.registry.service_discovery.v1.Node.leadership_status:type_name -> core.registry.service_discovery.v1.LeadershipStatus
	21, // 7: core.registry.service_discovery.v1.InitializeResponse.process_identity:type_name -> core.registry.service_discovery.v1.ProcessIdentity
	22, // 8: core.registry.service_discovery.v1.InitializeResponse.configuration:type_name -> core.registry.service_discovery.v1.StartupConfiguration
	7,  // 9: core.registry.service_discovery.v1.QueryRequest.filter:type_name -> core.registry.service_discovery.v1.Filter
	15, // 10: core.registry.service_discovery.v1.QueryResponse.data:type_name -> core.registry.service_discovery.v1.QueryResponse.DataEntry
	23, // 11: core.registry.service_discovery.v1.WatchResponse.process:type_name -> core.registry.service_discovery.v1.Process
	23, // 12: core.registry.service_discovery.v1.QueryResponse.DataEntry.value:type_name -> core.registry.service_discovery.v1.Process
	4,  // 13: core.registry.service_discovery.v1.ServiceDiscoveryService.Initialize:input_type -> core.registry.service_discovery.v1.InitializeRequest
	1,  // 14: core.registry.service_discovery.v1.ServiceDiscoveryService.Synchronize:input_type -> core.registry.service_discovery.v1.ClientDetails
	9,  // 15: core.registry.service_discovery.v1.ServiceDiscoveryService.Finalize:input_type -> core.registry.service_discovery.v1.FinalizeRequest
	11, // 16: core.registry.service_discovery.v1.ServiceDiscoveryService.ReportHealth:input_type -> core.registry.service_discovery.v1.ReportHealthRequest
	6,  // 17: core.registry.service_discovery.v1.ServiceDiscoveryService.Query:input_type -> core.registry.service_discovery.v1.QueryRequest
	13, // 18: core.registry.service_discovery.v1.ServiceDiscoveryService.Watch:input_type -> core.registry.service_discovery.v1.WatchRequest
	5,  // 19: core.registry.service_discovery.v1.ServiceDiscoveryService.Initialize:output_type -> core.registry.service_discovery.v1.InitializeResponse
	2,  // 20: core.registry.service_discovery.v1.ServiceDiscoveryService.Synchronize:output_type -> core.registry.service_discovery.v1.ClusterDetails
	10, // 21: core.registry.service_discovery.v1.ServiceDiscoveryService.Finalize:output_type -> core.registry.service_discovery.v1.FinalizeResponse
	12, // 22: core.registry.service_discovery.v1.ServiceDiscoveryService.ReportHealth:output_type -> core.registry.service_discovery.v1.ReportHealthResponse
	8,  // 23: core.registry.service_discovery.v1.ServiceDiscoveryService.Query:output_type -> core.registry.service_discovery.v1.QueryResponse
	14, // 24: core.registry.service_discovery.v1.ServiceDiscoveryService.Watch:output_type -> core.registry.service_discovery.v1.WatchResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_core_registry_service_discovery_v1_service_proto_init() }
func file_core_registry_service_discovery_v1_service_proto_init() {
	if File_core_registry_service_discovery_v1_service_proto != nil {
		return
	}
	file_core_registry_service_discovery_v1_models_proto_init()
	file_core_registry_service_discovery_v1_service_proto_msgTypes[6].OneofWrappers = []any{
		(*Filter_Id)(nil),
		(*Filter_Group)(nil),
		(*Filter_All)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_registry_service_discovery_v1_service_proto_rawDesc), len(file_core_registry_service_discovery_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_registry_service_discovery_v1_service_proto_goTypes,
		DependencyIndexes: file_core_registry_service_discovery_v1_service_proto_depIdxs,
		EnumInfos:         file_core_registry_service_discovery_v1_service_proto_enumTypes,
		MessageInfos:      file_core_registry_service_discovery_v1_service_proto_msgTypes,
	}.Build()
	File_core_registry_service_discovery_v1_service_proto = out.File
	file_core_registry_service_discovery_v1_service_proto_goTypes = nil
	file_core_registry_service_discovery_v1_service_proto_depIdxs = nil
}
