# Service - high level metadata for the process
service:
  name: host 
  default_port: 8080
  static_files_directory: "./web-client/build"

registry:
  url: "http://localhost:8500"

# ROUTES: A map of routes, 
http_routes:
  - path: /home/app
    handler_method: method_name
    http_method: GET
    
# REPOS: A list of configurations for a thick client that will include repo integrations for each db type.
# A repo in this system is defined as a persistence layer like the following:
# *[CockroachDB](https://www.cockroachlabs.com/docs/stable/developer-guide-overview.html)
# *[ScyllaDB](https://docs.scylladb.com/)
# *[Postgres](https://www.postgresql.org/)
#
# Implementations:
# * postgres (Sql database) 
# 
# * cockroachdb (Distributed Sql database)
# * scylladb (NoSql database)
# * clickhoust (olap dbms)
# 

# repos:
#   postgres:
#     db_type: postgres
#     protocol: postgresql
#     user: draft
#     domain: localhost
#     port: 26257
#     server: draft
#     log_mode: true
#     ssl: false

# PRODUCERS: A list of configurations for 
# Implementations:
# * nats
# * redpanda

# GATEWAYS: A list of external services that a service might want to communicate with types include
# * grpc      - services that can communicate using grpc 
# Gateways:
#   users:
#     gatewayType: grpc
#     # downstream rpc address, and port config
#     address: localhost
#     port: 50004
#     # @TODO: implement, currently everything is insecure
#     # optional, represents a path to the .crt for the service
#     tlsCert: certs/server.crt
#     # optional, represent a path to the .key for the service
#     tlsKey: certs/server.key
