name: api - CI

on:
  pull_request:
    branches:
      - master
    paths:
      - api/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  lint-breaking:
    name: Lint and Breaking Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.33.0"

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: api

      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: api
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=master,subdir=api"
