name: services - CI

on:
  pull_request:
    branches:
      - master
    paths:
      - services/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  changed:
    name: Prepare
    uses: ./.github/workflows/changes.yml
    with:
      path: services
      dir_names_max_depth: 2

  build-and-test:
    name: Build-Test (${{ matrix.service-path }})
    needs: [changed]
    runs-on: ubuntu-latest
    if: needs.changed.outputs.any_changed == 'true'
    strategy:
      matrix:
        go-version: ['1.21.x']
        service-path: ${{ fromJSON(needs.changed.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        if: matrix.service-path == 'core/blueprint'
        with:
          node-version: 18
          cache-dependency-path: services/${{ matrix.service-path }}/web-client/package-lock.json

      - name: Install Node dependencies
        if: matrix.service-path == 'core/blueprint'
        run: |
          cd services/${{ matrix.service-path }}/web-client &&
          npm i -D @swc/cli @swc/core &&
          npm install

      - name: Build web-client
        if: matrix.service-path == 'core/blueprint'
        run: |
          cd services/${{ matrix.service-path }}/web-client &&
          npm run build

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: services/${{ matrix.service-path }}/go.sum

      - name: Test
        working-directory: services/${{ matrix.service-path }}
        run: go test ./...

      - name: Build
        working-directory: services/${{ matrix.service-path }}
        run: go build main.go
