services:
  blueprint:
    image: ghcr.io/steady-bytes/draft-core-blueprint:latest
    restart: unless-stopped
    ports:
      - 2221:2221
      - 1111:1111
    volumes:
      - ./blueprint.yaml:/etc/config.yaml
  fuse:
    image: ghcr.io/steady-bytes/draft-core-fuse:latest
    restart: unless-stopped
    ports:
      - 18000:18000
    volumes:
      - ./fuse.yaml:/etc/config.yaml
  catalyst:
    image: ghcr.io/steady-bytes/draft-core-catalyst:latest
    restart: unless-stopped
    ports:
      - 2220:2220
    volumes:
      - ./catalyst.yaml:/etc/config.yaml
  # envoy:
  #   image: envoyproxy/envoy:v1.31.2
